/** Lint rules. */

import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      // `output: 'export'` writes a built copy of the app here.
      '**/out/**',
      'schema/**',
      'docs/**',
      // Authored mod JavaScript is third-party content.
      'mods/**',
      // Generated by Next on every build.
      'apps/editor/next-env.d.ts',
      'apps/play/next-env.d.ts',
      'apps/site/next-env.d.ts',
    ],
  },

  // Type-aware linting everywhere.
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // A leading underscore means "required by the shape, not needed here".
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // A dropped promise in a reducer is a state change that silently does not happen.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',

      // `any` defeats the strict settings in tsconfig.base.json.
      '@typescript-eslint/no-explicit-any': 'warn',

      // These fire constantly on well-typed code that reads unknown JSON.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',

      // `??
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',

      // Off after measuring: sixty-seven findings, of which one was real.
      '@typescript-eslint/no-base-to-string': 'off',

      // `CollectionPath | string` is deliberate: autocomplete plus a computed path.
      '@typescript-eslint/no-redundant-type-constituents': 'off',

      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': 'error',
      'prefer-const': 'error',
      'no-var': 'error',
    },
  },

  /** The shared packages must stay isomorphic, so a browser surface is a UI layer rather than a rewrite. */
  {
    files: [
      'packages/engine/src/**/*.ts',
      'packages/play/src/**/*.ts',
      'packages/mods/src/**/*.ts',
      'packages/module/src/**/*.ts',
      'packages/core/src/**/*.ts',
      'packages/library/src/**/*.ts',
    ],
    ignores: [
      'packages/engine/src/**/*.test.ts',
      'packages/play/src/**/*.test.ts',
      'packages/module/src/**/*.test.ts',
      'packages/core/src/**/*.test.ts',
      'packages/library/src/**/*.test.ts',
      // The one file allowed to read a module off disk, and the tools that write them.
      'packages/module/src/load.ts',
      'packages/module/src/bin/**/*.ts',
      // The mod runtime runs in a browser too, except `load.ts`.
      'packages/mods/src/**/*.test.ts',
      'packages/mods/src/load.ts',
      'packages/mods/src/testing.ts',
      // Authoring tools run on a developer's machine, never in a browser.
      'packages/mods/src/bin/**/*.ts',
    ],
    rules: {
      'no-restricted-globals': [
        'error',
        { name: 'process', message: 'This package runs in the browser — Node APIs belong in `src/bin/**` or `@dm/module/load`.' },
        { name: '__dirname', message: 'This package runs in the browser — Node APIs belong in `src/bin/**` or `@dm/module/load`.' },
        { name: 'require', message: 'This package runs in the browser — Node APIs belong in `src/bin/**` or `@dm/module/load`.' },
      ],
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: ['node:*', 'fs', 'path', 'os'], message: 'This package runs in the browser — Node APIs belong in `src/bin/**` or `@dm/module/load`.' },
            { group: ['picocolors'], message: 'The play layer emits data, not escape codes — colour belongs to the front end.' },
          ],
        },
      ],
    },
  },

  /** Command-line entry points are the one place printing is the whole job. */
  {
    files: ['packages/*/src/bin/**/*.ts'],
    rules: { 'no-console': 'off' },
  },

  /** The rules of hooks, in the two apps that have components. */
  {
    files: ['apps/*/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  /** Tests reach into internals on purpose, so the strictest promise rules only add noise. */
  {
    files: ['**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/unbound-method': 'off',
    },
  },
);
