/**
 * Lint rules.
 *
 * The compiler already enforces types; this catches the things it cannot — a
 * floating promise, a comparison that is always true, a Node API smuggled into
 * the engine. Rules earn their place by having caught something real or by
 * guarding a decision this codebase has already made; style opinions that a
 * reviewer would not raise are left out, because a warning nobody acts on
 * trains people to ignore warnings.
 *
 * Run with `npm run lint`, or `npm run check` alongside the typecheck and tests.
 */

import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      'schema/**',
      'docs/**',
      // Generated by Next on every build.
      'apps/editor/next-env.d.ts',
      'apps/play/next-env.d.ts',
    ],
  },

  // Type-aware linting everywhere. The project service picks up the same
  // tsconfigs the editor uses, so lint and the red squigglies agree.
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Unused code is dead weight, but a deliberately-ignored argument is not:
      // an underscore is the established way of saying "required by the shape,
      // not needed here", and this codebase uses it throughout.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // A dropped promise in a reducer is a state change that silently does not
      // happen. Worth an error every time.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',

      // `any` defeats the point of the strict settings in tsconfig.base.json.
      // Warn rather than error: the DSL boundary legitimately deals in values
      // whose shape is only known at runtime, and those are annotated as such.
      '@typescript-eslint/no-explicit-any': 'warn',

      // These fire constantly on well-typed code that reads unknown JSON, which
      // is most of the module layer's job.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',

      // `?? ''` on a value the compiler thinks is always defined is usually a
      // guard against bad module JSON, which the types describe optimistically.
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',

      // Off after measuring it: sixty-seven findings, of which exactly one was
      // real (a DSL value that could have been an object, now routed through
      // `expectString`). The rest are `String(row['id'])` while walking a
      // document the schema has already proven holds strings there, and
      // `compileModule` refuses documents where it does not. A rule that is
      // wrong ninety-eight times out of a hundred teaches people to skim past
      // lint output, which costs more than it catches.
      '@typescript-eslint/no-base-to-string': 'off',

      // `CollectionPath | string` is deliberate: the union gives an author
      // autocomplete for the real collection names while still accepting a
      // computed path. Collapsing to `string` is the point, not an oversight.
      '@typescript-eslint/no-redundant-type-constituents': 'off',

      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': 'error',
      'prefer-const': 'error',
      'no-var': 'error',
    },
  },

  /**
   * The engine must stay isomorphic, so that a browser play surface is a UI
   * layer rather than a rewrite. `tsconfig.isomorphic.json` already fails the
   * build on this; the rule exists as well because a lint error names the
   * reason at the line, and finding out at review time beats finding out from
   * a compiler flag whose purpose has to be looked up.
   */
  {
    files: ['packages/engine/src/**/*.ts', 'packages/play/src/**/*.ts'],
    ignores: ['packages/engine/src/**/*.test.ts', 'packages/play/src/**/*.test.ts'],
    rules: {
      'no-restricted-globals': [
        'error',
        { name: 'process', message: 'The engine and the play layer are isomorphic — Node APIs belong in the app layer or `@dm/module/load`.' },
        { name: '__dirname', message: 'The engine and the play layer are isomorphic — Node APIs belong in the app layer or `@dm/module/load`.' },
        { name: 'require', message: 'The engine and the play layer are isomorphic — Node APIs belong in the app layer or `@dm/module/load`.' },
      ],
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: ['node:*', 'fs', 'path', 'os'], message: 'The engine and the play layer are isomorphic — Node APIs belong in the app layer or `@dm/module/load`.' },
            { group: ['picocolors'], message: 'The play layer emits data, not escape codes — colour belongs to the front end.' },
          ],
        },
      ],
    },
  },

  /**
   * Command-line entry points are the one place printing is the whole job.
   */
  {
    files: ['packages/*/src/bin/**/*.ts'],
    rules: { 'no-console': 'off' },
  },

  /**
   * Tests reach into internals on purpose and assert on shapes the compiler
   * cannot narrow, so the strictest promise rules would only add noise.
   */
  {
    files: ['**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/unbound-method': 'off',
    },
  },
);
