/**
 * Lint rules.
 *
 * The compiler already enforces types; this catches what it cannot — a floating promise, a
 * comparison that is always true, a Node API smuggled into the engine. Rules earn their place by
 * having caught something real or by guarding a decision this codebase has made; a warning nobody
 * acts on trains people to ignore warnings.
 *
 * Run with `npm run lint`, or `npm run check` alongside the typecheck and tests.
 */

import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      // `output: 'export'` writes a built copy of the app here.
      '**/out/**',
      'schema/**',
      'docs/**',
      // Authored mod JavaScript is third-party content. It belongs to no tsconfig project, so type-
      // aware linting would error on every file.
      'mods/**',
      // Generated by Next on every build.
      'apps/editor/next-env.d.ts',
      'apps/play/next-env.d.ts',
      'apps/site/next-env.d.ts',
    ],
  },

  // Type-aware linting everywhere. The project service picks up the same tsconfigs the editor uses,
  // so lint and the red squigglies agree.
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Unused code is dead weight, but a leading underscore means "required by the shape, not
      // needed here".
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // A dropped promise in a reducer is a state change that silently does not happen.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',

      // `any` defeats the strict settings in tsconfig.base.json. A warning rather than an error:
      // the DSL boundary deals in values whose shape is only known at runtime.
      '@typescript-eslint/no-explicit-any': 'warn',

      // These fire constantly on well-typed code that reads unknown JSON, which is most of the
      // module layer's job.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',

      // `?? ''` on a value the compiler thinks is always defined is usually a guard against bad
      // module JSON, which the types describe optimistically.
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',

      // Off after measuring: sixty-seven findings, of which one was real. The rest are
      // `String(row['id'])` while walking a document the schema has already proven holds strings
      // there.
      '@typescript-eslint/no-base-to-string': 'off',

      // `CollectionPath | string` is deliberate: the union gives autocomplete for the real
      // collection names while still accepting a computed path.
      '@typescript-eslint/no-redundant-type-constituents': 'off',

      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': 'error',
      'prefer-const': 'error',
      'no-var': 'error',
    },
  },

  /**
   * The shared packages must stay isomorphic, so a browser surface is a UI layer rather than a
   * rewrite. `tsconfig.isomorphic.json` already fails the build on this; the rule exists too
   * because a lint error names the reason at the line.
   *
   * `@dm/module` and `@dm/core` are held to it as well, because the studio and the player compile,
   * split, hash and store documents entirely in the browser. The filesystem lives in
   * `@dm/module/load` and `src/bin/**`.
   */
  {
    files: [
      'packages/engine/src/**/*.ts',
      'packages/play/src/**/*.ts',
      'packages/mods/src/**/*.ts',
      'packages/module/src/**/*.ts',
      'packages/core/src/**/*.ts',
      'packages/library/src/**/*.ts',
    ],
    ignores: [
      'packages/engine/src/**/*.test.ts',
      'packages/play/src/**/*.test.ts',
      'packages/module/src/**/*.test.ts',
      'packages/core/src/**/*.test.ts',
      'packages/library/src/**/*.test.ts',
      // The one file allowed to read a module off disk, which is why it is a separate export entry,
      // and the tools that write them.
      'packages/module/src/load.ts',
      'packages/module/src/bin/**/*.ts',
      // The mod runtime has to run in a browser too, except `load.ts`, which is the one file
      // allowed to read a mod off disk.
      'packages/mods/src/**/*.test.ts',
      'packages/mods/src/load.ts',
      'packages/mods/src/testing.ts',
      // Authoring tools run on a developer's machine, never in a browser.
      'packages/mods/src/bin/**/*.ts',
    ],
    rules: {
      'no-restricted-globals': [
        'error',
        { name: 'process', message: 'This package runs in the browser — Node APIs belong in `src/bin/**` or `@dm/module/load`.' },
        { name: '__dirname', message: 'This package runs in the browser — Node APIs belong in `src/bin/**` or `@dm/module/load`.' },
        { name: 'require', message: 'This package runs in the browser — Node APIs belong in `src/bin/**` or `@dm/module/load`.' },
      ],
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: ['node:*', 'fs', 'path', 'os'], message: 'This package runs in the browser — Node APIs belong in `src/bin/**` or `@dm/module/load`.' },
            { group: ['picocolors'], message: 'The play layer emits data, not escape codes — colour belongs to the front end.' },
          ],
        },
      ],
    },
  },

  /** Command-line entry points are the one place printing is the whole job. */
  {
    files: ['packages/*/src/bin/**/*.ts'],
    rules: { 'no-console': 'off' },
  },

  /**
   * The rules of hooks, in the two apps that have components.
   *
   * A conditional hook crashes the whole page and neither the typecheck nor the tests can catch it:
   * the tests run in a node environment with no DOM, and the compiler has no idea `useMemo` is
   * special.
   *
   * `exhaustive-deps` stays a warning: a dependency deliberately keyed by value rather than
   * identity is a real pattern here, and an error would make it unwritable.
   */
  {
    files: ['apps/*/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  /**
   * Tests reach into internals on purpose and assert on shapes the compiler cannot narrow, so the
   * strictest promise rules would only add noise.
   */
  {
    files: ['**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/unbound-method': 'off',
    },
  },
);
