/**
 * One line per field, saying what it is.
 *
 * The Zod schemas already carry the type, whether a field is required, and its
 * default, and `walkModuleSchema` reads all three straight off them. What they
 * cannot carry is a sentence for a person: `.describe()` is the only annotation
 * slot Zod gives a string, and `ref:` took it. So the prose lives here, keyed by
 * the canonical path the walk produces.
 *
 * `fieldDocs.test.ts` holds this file to the schema in both directions. Every
 * field must have a line, and no line may name a field that no longer exists,
 * so adding to the format means describing the addition and removing from it
 * cannot leave litter behind.
 *
 * Style, because a thousand of these are only readable if they are uniform:
 * one sentence, the shortest that is still true, and the trap rather than the
 * obvious meaning wherever a field has one.
 */

export const FIELD_DOCS: Record<string, string> = {
  // ---------------------------------------------------------------- document
  'format': 'Version of the module format itself, so a later reader knows how to migrate.',
  'id': 'Id of the module. Saves record it and refuse to load against a different one.',
  'version': 'Semantic version of this module, as 1.0.0.',
  'engine': 'Engine version range this module expects.',
  'extends': 'Base module to layer on, as id@version. Loaded first, this document merged over it.',
  'mods': 'Mods this game expects, pinned by id and content hash.',
  'meta': 'Title, author, and the rest of the shelf entry.',
  'rules': 'The system. Attributes, resources, conditions, dice, progression.',
  'content': 'The things. Abilities, items, monsters, NPCs, factions.',
  'world': 'The places. Biomes, areas, points of interest, dungeons, maps.',
  'narrative': 'The story. Text, dialogue, quests, lore, memory.',
  'start': 'Party size, character creation, and where play begins.',

  // -------------------------------------------------------------------- mods
  'mods.id': 'Id of the mod, matching its folder under mods/.',
  'mods.hash': 'Content hash of the mod as pinned. A drifted mod is reported, not run silently.',
  'mods.target': 'Whether the mod attaches to the engine at play time or to the editor.',
  'mods.required': 'True when the game does not run without it. False lets play continue unmodded.',
  'mods.note': 'What to say if the mod is missing or drifted. The author\'s own words.',

  // -------------------------------------------------------------------- meta
  'meta.title': 'Display name of the game.',
  'meta.author': 'Who wrote it.',
  'meta.description': 'A sentence or two for the shelf.',
  'meta.tags': 'Free labels for filtering and search.',
  'meta.license': 'License string. Carried, never interpreted.',

  // ------------------------------------------------------------------- rules
  'rules.attributes': 'What a character is made of. At least one is required.',
  'rules.resources': 'Pools that go up and down. Hit points and focus are both just resources.',
  'rules.derivedStats': 'Numbers computed from attributes, gear, and conditions.',
  'rules.damageTypes': 'The kinds of damage that exist. Resistance and immunity are written against these.',
  'rules.conditions': 'States a creature can be in, with what they do while they last.',
  'rules.actionTypes': 'The action economy. Each type declares how many a creature gets per turn.',
  'rules.equipmentSlots': 'Where gear goes, and how many items each place holds.',
  'rules.itemProperties': 'Reusable tags on items that carry stat modifiers.',
  'rules.masteryTiers': 'Named skill bands, so a requirement can ask for adept rather than rank 5.',
  'rules.rests': 'The ways a party recovers, and what each costs in time.',
  'rules.resolution': 'The dice convention. What a check rolls, what crits, how results round.',
  'rules.progression': 'The level curve and what each level grants. Required.',
  'rules.savingThrows': 'The saves that exist, each governed by an attribute.',
  'rules.sizes': 'Creature sizes, with the space they take and how far they reach.',
  'rules.creatureTypes': 'Broad kinds of creature, for gating and description.',
  'rules.senses': 'How creatures notice each other. Sight, scent, hearing, or anything you invent.',
  'rules.stances': 'Postures a creature can take, trading speed for concealment or the reverse.',
  'rules.movementModes': 'Ways of moving, each with a base speed and a terrain multiplier.',
  'rules.languages': 'Languages that exist. Creatures list which they speak.',
  'rules.alignments': 'Moral or factional labels. Carried and gateable, never enforced.',
  'rules.opportunities': 'Reactions the rules grant everyone, such as a parting blow.',
  'rules.coverTypes': 'Degrees of cover and what each is worth on defence.',
  'rules.spellcasting': 'Slots or points, concentration, components, and rituals.',
  'rules.perception': 'Which sense counts as sight, and the defaults perception runs on.',
  'rules.currency': 'What money is called and whether it can go negative.',
  'rules.vitalResource': 'The resource whose floor means death. Required.',
  'rules.initiativeStat': 'Derived stat rolled for turn order. Without one, order is by id.',
  'rules.defaultSize': 'Size given to a creature that names none.',
  'rules.defaultMovementMode': 'Movement mode used when a creature names none.',
  'rules.interactionRange': 'How close you must be to talk to someone or reach a thing.',
  'rules.search': 'How far a search finds traps and how close disarming needs you.',
  'rules.dispositionBands': 'Disposition numbers to stances. A band above 0 is the only way to get allies.',
  'rules.extra': 'Open bag of your own data on the ruleset. Read it back with a ref path.',

  'rules.attributes.id': 'Id of the attribute, used as actor.attr.<id>.',
  'rules.attributes.name': 'Display name.',
  'rules.attributes.abbrev': 'Short form for tight displays, one to six characters.',
  'rules.attributes.description': 'What this attribute covers. Author and player facing.',
  'rules.attributes.min': 'Lowest value character creation and effects may take it to.',
  'rules.attributes.max': 'Highest value it may reach.',
  'rules.attributes.default': 'Starting value before creation spends any points.',
  'rules.attributes.modifier': 'Formula turning the raw value into a modifier. Sees only value.',

  'rules.resources.id': 'Id of the resource, used as actor.res.<id>.',
  'rules.resources.name': 'Display name.',
  'rules.resources.description': 'What the pool represents.',
  'rules.resources.max': 'Formula for the ceiling. May read attributes, modifiers, and level.',
  'rules.resources.min': 'Formula for the floor. Reaching it runs onDepleted.',
  'rules.resources.initial': 'Formula for the starting value. Defaults to the maximum.',
  'rules.resources.restoreOnShortRest': 'Fraction of the maximum a short rest returns, 0 to 1.',
  'rules.resources.restoreOnLongRest': 'Fraction of the maximum a long rest returns, 0 to 1.',
  'rules.resources.onDepleted': 'What happens at the floor. Death is these effects on the vital resource.',

  'rules.derivedStats.id': 'Id of the stat, used as actor.derived.<id>.',
  'rules.derivedStats.name': 'Display name.',
  'rules.derivedStats.description': 'What the number means.',
  'rules.derivedStats.formula': 'Expression over attributes, modifiers, level, and resources.',

  'rules.damageTypes.id': 'Id of the damage type.',
  'rules.damageTypes.name': 'Display name.',
  'rules.damageTypes.description': 'What this kind of harm is.',
  'rules.damageTypes.tags': 'Labels a damage interaction can except on, such as silvered.',

  'rules.conditions.id': 'Id of the condition, used as actor.conditions.<id>.',
  'rules.conditions.name': 'Display name.',
  'rules.conditions.description': 'What being in this state means.',
  'rules.conditions.tags': 'Free labels for grouping and gating.',
  'rules.conditions.stacking': 'What a second application does. Refresh, extend, stack, or ignore.',
  'rules.conditions.defaultDuration': 'Rounds it lasts when the applying effect names no duration.',
  'rules.conditions.onApply': 'Effects run once, when it lands.',
  'rules.conditions.onTick': 'Effects run at the start of each of the sufferer\'s turns.',
  'rules.conditions.onExpire': 'Effects run once, when it ends.',
  'rules.conditions.modifiers': 'Derived stat adjustments while it holds. Magnitude is in scope.',
  'rules.conditions.prevents': 'Action type ids this forbids. A bare id, not a checked reference.',
  'rules.conditions.suppressesSenses': 'Senses this shuts off, unless the sense itself ignores this condition.',
  'rules.conditions.swings': 'Which way the dice lean while this is on you. Prefer it or modifiers, not both.',
  'rules.conditions.swings.ownAttacks': 'How attack rolls made by the afflicted creature lean.',
  'rules.conditions.swings.attacksAgainstSelf': 'How attack rolls made against the afflicted creature lean.',
  'rules.conditions.swings.checks': 'How the afflicted creature\'s ability checks lean.',
  'rules.conditions.swings.saves': 'How the afflicted creature\'s saving throws lean.',
  'rules.conditions.concealsIdentity': 'Makes a witness less able to name who did the deed.',
  'rules.conditions.savingThrow': 'A save to shrug it off, and when that save is offered.',
  'rules.conditions.implies': 'Condition ids that come with this one. A bare id, not a checked reference.',
  'rules.conditions.extra': 'Open bag of your own data on this condition.',

  'rules.conditions.savingThrow.save': 'Which saving throw resists it.',
  'rules.conditions.savingThrow.difficulty': 'Difficulty of that save, as an expression.',
  'rules.conditions.savingThrow.timing': 'When the save is offered. On landing, on turn ends, or both.',

  'rules.actionTypes.id': 'Id of the action type, such as action or bonus.',
  'rules.actionTypes.name': 'Display name.',
  'rules.actionTypes.description': 'What this slice of a turn is for.',
  'rules.actionTypes.perTurn': 'How many a creature gets each turn.',

  'rules.equipmentSlots.id': 'Id of the slot, named by an item\'s slot field.',
  'rules.equipmentSlots.name': 'Display name.',
  'rules.equipmentSlots.capacity': 'How many items fit here at once.',

  'rules.itemProperties.id': 'Id of the property, named by an item\'s properties list.',
  'rules.itemProperties.name': 'Display name.',
  'rules.itemProperties.description': 'What carrying this property means.',
  'rules.itemProperties.modifiers': 'Derived stat adjustments an item with this property grants.',
  'rules.itemProperties.attackStats': 'Attributes a weapon with this may also attack with. The best is used, for damage too.',
  'rules.itemProperties.extra': 'Open bag of your own data on this property.',

  'rules.masteryTiers.id': 'Id of the tier, asked for by a requirement as minTier.',
  'rules.masteryTiers.name': 'Display name.',
  'rules.masteryTiers.description': 'What this level of skill means.',
  'rules.masteryTiers.atRank': 'Skill rank at which the tier is reached.',

  'rules.rests.id': 'Id of the rest, named by a rest action and by spellcasting recovery.',
  'rules.rests.name': 'Display name.',
  'rules.rests.description': 'What this kind of rest is.',
  'rules.rests.duration': 'Minutes of world time it consumes.',
  'rules.rests.kind': 'Whether resources use their short rest or long rest fraction.',
  'rules.rests.effects': 'Extra effects run on finishing, beyond resource restoration.',
  'rules.rests.interruptChance': 'Chance per rest that something interrupts it, 0 to 1.',

  'rules.resolution.checkDice': 'The notation every check rolls.',
  'rules.resolution.advantageDice': 'Notation rolled instead when a check has advantage.',
  'rules.resolution.disadvantageDice': 'Notation rolled instead when a check has disadvantage.',
  'rules.resolution.swingStacking': 'What a roll does with more than one swing: cancel them out, or go by the count.',
  'rules.resolution.criticalSuccessAt': 'Natural roll at or above which a check crits. Null for no crits.',
  'rules.resolution.criticalFailureAt': 'Natural roll at or below which a check fumbles. Null for no fumbles.',
  'rules.resolution.criticalScope': 'Which kinds of roll can crit or fumble: attack, save, check.',
  'rules.resolution.criticalDamageMultiplier': 'What a critical hit multiplies damage by.',
  'rules.resolution.saveSuccessMultiplier': 'Damage kept on a successful save when the ability says half.',
  'rules.resolution.passiveBase': 'Number a passive score adds its modifier to instead of rolling.',
  'rules.resolution.opposedMode': 'Whether an opposed check rolls both sides or rolls against a passive score.',
  'rules.resolution.damageRounding': 'How fractional damage resolves to a whole number.',
  'rules.resolution.reputationRounding': 'How fractional reputation change resolves to a whole number.',
  'rules.resolution.defaultDifficulty': 'Difficulty used when a check names none.',
  'rules.resolution.attackBonus': 'What a weapon attack adds. Omitted, just the attribute modifier, which never grows.',
  'rules.resolution.difficulties': 'Named difficulties, so content can ask for hard rather than 18.',

  'rules.progression.maxLevel': 'Level the curve stops at. Experience past it is kept but grants nothing.',
  'rules.progression.levels': 'One entry per level, in order, with its cost and what it gives.',
  'rules.progression.proficiency': 'Formula for the proficiency bonus over actor.level.',
  'rules.progression.proficiencyRank': 'Skill rank a proficiency counts as when a requirement asks.',
  'rules.progression.levelVitality': 'How the vital resource grows on gaining a level.',

  'rules.progression.levels.level': 'Which level this entry describes.',
  'rules.progression.levels.xpRequired': 'Total experience needed to reach it.',
  'rules.progression.levels.grants': 'Effects run on each character crossing this level.',

  'rules.progression.levelVitality.policy': 'Roll the die, take its average, take its maximum, or grant nothing.',
  'rules.progression.levelVitality.die': 'Whether the die comes from the character\'s class or their size.',
  'rules.progression.levelVitality.bonus': 'Expression added on top of the die, per level.',

  'rules.savingThrows.id': 'Id of the save, named by abilities and conditions.',
  'rules.savingThrows.name': 'Display name.',
  'rules.savingThrows.description': 'What this save resists.',
  'rules.savingThrows.attribute': 'Attribute whose modifier the save adds.',
  'rules.savingThrows.defaultDifficulty': 'Difficulty used when the thing calling for the save names none.',
  'rules.savingThrows.extra': 'Open bag of your own data on this save.',

  'rules.sizes.id': 'Id of the size.',
  'rules.sizes.name': 'Display name.',
  'rules.sizes.space': 'Distance units the creature occupies. Converted to tiles by the engine.',
  'rules.sizes.reach': 'Distance units the creature can reach to strike.',
  'rules.sizes.carryMultiplier': 'Not read by the engine. Build encumbrance from actor.carried and a derived stat.',
  'rules.sizes.hitDie': 'Vitality die for creatures of this size, when levelVitality takes its die from size.',
  'rules.sizes.extra': 'Open bag of your own data on this size.',

  'rules.creatureTypes.id': 'Id of the creature type.',
  'rules.creatureTypes.name': 'Display name.',
  'rules.creatureTypes.description': 'What this kind of creature is.',
  'rules.creatureTypes.tags': 'Free labels for grouping and gating.',
  'rules.creatureTypes.extra': 'Open bag of your own data on this creature type.',

  'rules.senses.id': 'Id of the sense, used as a key in emits and in a creature\'s senses.',
  'rules.senses.name': 'Display name.',
  'rules.senses.description': 'What this sense picks up.',
  'rules.senses.defaultRange': 'Distance units a creature perceives with it unless it says otherwise.',
  'rules.senses.ignores': 'Not read by the engine yet. No condition currently suppresses a sense.',
  'rules.senses.propagation': 'Whether the signal travels in a straight line or fills the space.',
  'rules.senses.blockedBy': 'What stops it. Opaque terrain, anything impassable, or nothing.',
  'rules.senses.falloff': 'Whether strength drops off a cliff at range or fades with distance.',
  'rules.senses.lingerMinutes': 'How long a trace stays after whatever left it has gone. Scent, not sight.',
  'rules.senses.spreadPerMinute': 'How far a trace creeps outward each minute.',
  'rules.senses.spreadRetention': 'Strength kept as a trace spreads, 0 to 1.',
  'rules.senses.rememberMinutes': 'How long a creature holds on to something it noticed with this sense.',
  'rules.senses.impressionTextKey': 'Text pool for a clear impression.',
  'rules.senses.faintImpressionTextKey': 'Text pool for a weak impression.',
  'rules.senses.emptyTextKey': 'Text pool for sensing and finding nothing.',
  'rules.senses.thresholds': 'Signal strengths at which noticing turns into investigating and then attacking.',
  'rules.senses.extra': 'Open bag of your own data on this sense.',

  'rules.senses.thresholds.detect': 'Strength at which the creature knows something is there, 0 to 1.',
  'rules.senses.thresholds.investigate': 'Strength at which it goes to look, 0 to 1.',
  'rules.senses.thresholds.aggro': 'Strength at which it treats the source as a target, 0 to 1.',

  'rules.stances.id': 'Id of the stance.',
  'rules.stances.name': 'Display name.',
  'rules.stances.description': 'What moving this way means.',
  'rules.stances.speedMultiplier': 'What it does to movement speed.',
  'rules.stances.emits': 'Signal strength this stance gives off, per sense.',
  'rules.stances.concealedBy': 'Skill whose rank makes this stance quieter.',
  'rules.stances.concealmentPerPoint': 'Signal removed per rank of that skill.',
  'rules.stances.extra': 'Open bag of your own data on this stance.',

  'rules.movementModes.id': 'Id of the mode, such as walk, swim, or fly.',
  'rules.movementModes.name': 'Display name.',
  'rules.movementModes.defaultSpeed': 'Distance units per turn for a creature that names no speed of its own.',
  'rules.movementModes.terrainMultiplier': 'What this mode does to terrain movement costs.',
  'rules.movementModes.fallsWhenDisabled': 'Not read by the engine yet. Nothing takes a movement mode away.',
  'rules.movementModes.extra': 'Open bag of your own data on this mode.',

  'rules.languages.id': 'Id of the language.',
  'rules.languages.name': 'Display name.',
  'rules.languages.description': 'Who speaks it and where.',
  'rules.languages.script': 'Not read by the engine. The writing system, for flavour.',
  'rules.languages.exotic': 'Not read by the engine. Dialogue and readable content are not language gated.',
  'rules.languages.extra': 'Open bag of your own data on this language.',

  'rules.alignments.id': 'Id of the alignment.',
  'rules.alignments.name': 'Display name.',
  'rules.alignments.abbrev': 'Short form for tight displays.',
  'rules.alignments.extra': 'Open bag of your own data on this alignment.',

  'rules.opportunities.id': 'Id of the opportunity.',
  'rules.opportunities.name': 'Display name.',
  'rules.opportunities.description': 'What this reaction is and why everyone has it.',
  'rules.opportunities.on': 'What provokes it. Leaving reach, casting, shooting, standing, being hit, or custom.',
  'rules.opportunities.event': 'Event name to watch, when on is custom.',
  'rules.opportunities.actionType': 'Action type it spends. Without one it is free.',
  'rules.opportunities.use': 'Ability the reacting creature uses. Without one, only effects run.',
  'rules.opportunities.requires': 'Predicate that must hold for it to trigger. Not the requirement object.',
  'rules.opportunities.effects': 'Effects run when it triggers.',
  'rules.opportunities.usesPerRound': 'How many times one creature may take it each round.',
  'rules.opportunities.extra': 'Open bag of your own data on this opportunity.',

  'rules.coverTypes.id': 'Id of the cover type.',
  'rules.coverTypes.name': 'Display name.',
  'rules.coverTypes.defenceBonus': 'Added to the defended stat when the target has this cover.',
  'rules.coverTypes.blocksTargeting': 'True when the target cannot be picked at all, not merely harder to hit.',
  'rules.coverTypes.extra': 'Open bag of your own data on this cover type.',

  'rules.spellcasting.mode': 'Whether casting spends slots, spends points, both, or is off.',
  'rules.spellcasting.maxSpellLevel': 'Highest spell level the game has.',
  'rules.spellcasting.slotTable': 'Slots per spell level, keyed by caster level.',
  'rules.spellcasting.pointResource': 'Resource points are drawn from, when the mode uses points.',
  'rules.spellcasting.pointCosts': 'Point cost per spell level.',
  'rules.spellcasting.saveDifficulty': 'Formula for the difficulty of a save against a caster\'s spell.',
  'rules.spellcasting.attackBonus': 'Formula for a spell attack bonus, overriding the ordinary attack stat.',
  'rules.spellcasting.concentration': 'Whether holding a spell can be broken, and by what.',
  'rules.spellcasting.recoverOn': 'Which rests give slots back.',
  'rules.spellcasting.ritualCasting': 'Whether spells marked ritual can be cast without spending a slot.',
  'rules.spellcasting.componentActionTypes': 'Action types verbal and somatic components need free.',
  'rules.spellcasting.extra': 'Open bag of your own data on spellcasting.',

  'rules.spellcasting.concentration.enabled': 'Whether concentration exists at all.',
  'rules.spellcasting.concentration.savingThrow': 'Save rolled to keep concentration on taking damage.',
  'rules.spellcasting.concentration.difficulty': 'Difficulty of that save, as an expression.',
  'rules.spellcasting.concentration.maxConcurrent': 'How many concentration spells one caster may hold.',

  'rules.spellcasting.componentActionTypes.verbal': 'Action type a verbal component occupies.',
  'rules.spellcasting.componentActionTypes.somatic': 'Action type a somatic component occupies.',

  'rules.perception.sightSense': 'Which sense counts as sight, and so decides what the map shows as explored.',
  'rules.perception.curiosityMinutes': 'How long a creature keeps walking toward something it noticed.',
  'rules.perception.defaultStance': 'Stance a creature is in when it names none.',
  'rules.perception.minimumEmission': 'Signal below this is treated as nothing, 0 to 1.',
  'rules.perception.extra': 'Open bag of your own data on perception.',

  'rules.currency.name': 'What money is called in the plural.',
  'rules.currency.abbrev': 'Short form for tight displays.',
  'rules.currency.allowNegative': 'Whether the purse may go into debt.',

  'rules.interactionRange.talk': 'How many tiles away you can start a conversation.',
  'rules.interactionRange.reach': 'How many tiles away you can take, open, or otherwise handle a thing.',

  'rules.search.trapRadius': 'How many tiles a search sweeps for traps.',
  'rules.search.disarmReach': 'How many tiles away a trap can be disarmed from.',

  'rules.dispositionBands.id': 'Id of the band.',
  'rules.dispositionBands.atLeast': 'Lowest disposition in this band. The highest matching band wins.',
  'rules.dispositionBands.stance': 'How a creature in this band treats the party.',

  // ----------------------------------------------------------------- content
  'content.abilities': 'Anything a creature can actively do. Attacks, spells, shouts, tricks.',
  'content.skills': 'Trained proficiencies, each governed by an attribute.',
  'content.ancestries': 'What a character is born as, and what that gives them.',
  'content.classes': 'What a character trained as, and what each level of it grants.',
  'content.items': 'Everything carryable, wearable, usable, or sellable.',
  'content.lootTables': 'Weighted tables drawn for spoils, containers, and shop stock.',
  'content.monsters': 'Statblocks. NPCs point at one when they can fight.',
  'content.traps': 'Hazards placed in rooms, with how they are spotted and defused.',
  'content.factions': 'Groups that hold an opinion of the party.',
  'content.npcs': 'People. Who they are, where they live, and what they will talk about.',

  'content.abilities.id': 'Id of the ability.',
  'content.abilities.name': 'Display name.',
  'content.abilities.description': 'What using it looks like.',
  'content.abilities.tags': 'Free labels for grouping and gating.',
  'content.abilities.actionType': 'Action type it spends. Without one it costs nothing from the turn.',
  'content.abilities.costs': 'Resources spent per use, each as an expression.',
  'content.abilities.range': 'Distance units it reaches. 0 means touch.',
  'content.abilities.cooldown': 'Rounds before the same creature may use it again.',
  'content.abilities.requires': 'Who may use it at all. The gating vocabulary.',
  'content.abilities.when': 'Predicate checked at the moment of use, on top of requires.',
  'content.abilities.targeting': 'How many and which side it picks.',
  'content.abilities.attack': 'Makes it an attack roll, and says what it rolls against.',
  'content.abilities.savingThrow': 'Makes it a save instead, and says what a success is worth.',
  'content.abilities.spellLevel': 'Slot level it is cast at. Absent means it is not a spell.',
  'content.abilities.concentration': 'Whether holding it occupies the caster\'s concentration.',
  'content.abilities.ritual': 'Whether it can be cast slowly without spending a slot.',
  'content.abilities.castingTime': 'Free text for the sheet. Timing in play comes from actionType.',
  'content.abilities.duration': 'Free text for the sheet. Timing in play comes from the conditions it applies.',
  'content.abilities.components': 'What casting it needs. Verbal, somatic, material, or a focus.',
  'content.abilities.materialComponent': 'Item consumed or held as the material component.',
  'content.abilities.areaOfEffect': 'Shape and size when it covers ground rather than a target.',
  'content.abilities.upcast': 'Extra effects per slot level above its own.',
  'content.abilities.onUse': 'Effects run on a hit, a failed save, or unconditionally.',
  'content.abilities.onMiss': 'Effects run when the attack roll misses.',
  'content.abilities.onCritical': 'Effects run on a critical, in addition to the multiplied damage.',
  'content.abilities.extra': 'Open bag of your own data on this ability.',

  'content.abilities.requires.description': 'Why this gate exists. Shown in the editor and in refusals.',
  'content.abilities.requires.minLevel': 'Lowest character level that passes.',
  'content.abilities.requires.maxLevel': 'Highest character level that passes.',
  'content.abilities.requires.classes': 'Passes if the actor is any one of these classes.',
  'content.abilities.requires.ancestries': 'Passes if the actor is any one of these ancestries.',
  'content.abilities.requires.abilities': 'The actor must know all of these.',
  'content.abilities.requires.attributes': 'Attribute floors and ceilings the actor must sit inside.',
  'content.abilities.requires.skills': 'Skill ranks or mastery tiers the actor must have reached.',
  'content.abilities.requires.creatureTypes': 'Passes if the actor is any one of these creature types.',
  'content.abilities.requires.alignments': 'Passes if the actor is any one of these alignments.',
  'content.abilities.requires.languages': 'The actor must speak all of these.',
  'content.abilities.requires.currency': 'Money the actor must be carrying.',
  'content.abilities.requires.items': 'Items the actor must hold, optionally equipped or spent.',
  'content.abilities.requires.quests': 'Quests that must stand at a given status.',
  'content.abilities.requires.factions': 'Standing or rank the actor must hold with a faction.',
  'content.abilities.requires.memories': 'What someone must, or must not, know about a deed.',
  'content.abilities.requires.flags': 'World flags that must be set, or set to a value.',
  'content.abilities.requires.lore': 'Lore entries the actor must know.',
  'content.abilities.requires.without': 'What the actor must lack. As common as what they must have.',
  'content.abilities.requires.custom': 'Raw predicate for a gate the clauses cannot say.',
  'content.abilities.requires.anyOf': 'Alternatives. Any one branch passing satisfies the whole gate.',

  'content.abilities.requires.attributes.attribute': 'Which attribute is being checked.',
  'content.abilities.requires.attributes.min': 'Lowest value that passes.',
  'content.abilities.requires.attributes.max': 'Highest value that passes.',

  'content.abilities.requires.skills.skill': 'Which skill is being checked.',
  'content.abilities.requires.skills.minRank': 'Lowest trained rank that passes.',
  'content.abilities.requires.skills.minTier': 'Lowest mastery tier that passes, instead of naming a rank.',

  'content.abilities.requires.items.item': 'Which item is being checked.',
  'content.abilities.requires.items.quantity': 'How many are needed.',
  'content.abilities.requires.items.consume': 'True to spend them on passing. This is how a key is used up.',
  'content.abilities.requires.items.equipped': 'True when carrying is not enough and it must be worn or wielded.',

  'content.abilities.requires.quests.quest': 'Which quest is being checked.',
  'content.abilities.requires.quests.status': 'The status it must stand at. Unstarted means never taken.',
  'content.abilities.requires.quests.objective': 'Ask for one finished objective instead of the whole quest.',

  'content.abilities.requires.factions.faction': 'Which faction is being checked.',
  'content.abilities.requires.factions.minStanding': 'Lowest standing that passes.',
  'content.abilities.requires.factions.maxStanding': 'Highest standing that passes.',
  'content.abilities.requires.factions.minRank': 'Lowest rank that passes, instead of naming a number.',

  'content.abilities.requires.memories.deedKind': 'Which kind of deed is being asked about.',
  'content.abilities.requires.memories.who': 'Whose memory is consulted. The speaker, the party, anyone, or the faction.',
  'content.abilities.requires.memories.known': 'True to require they know it, false to require they do not.',
  'content.abilities.requires.memories.withinDays': 'Only count the memory if it is fresher than this.',

  'content.abilities.requires.flags.flag': 'Flag name. A free string, not a checked reference.',
  'content.abilities.requires.flags.equals': 'Value it must hold. Omit to require only that it is set.',

  'content.abilities.requires.lore.entry': 'Which lore entry is being checked.',
  'content.abilities.requires.lore.known': 'True to require it is known, false to require it is not.',

  'content.abilities.requires.without.classes': 'Fails if the actor is any of these classes.',
  'content.abilities.requires.without.abilities': 'Fails if the actor knows any of these.',
  'content.abilities.requires.without.items': 'Fails if the actor is carrying any of these.',
  'content.abilities.requires.without.quests': 'Fails if any of these quests stands at the named status.',
  'content.abilities.requires.without.flags': 'Fails if any of these flags is set.',
  'content.abilities.requires.without.conditions': 'Fails if the actor is under any of these conditions.',
  'content.abilities.requires.without.lore': 'Fails if the actor knows any of these lore entries.',

  'content.abilities.requires.anyOf.description': 'Why this branch exists. Shown in the editor.',
  'content.abilities.requires.anyOf.minLevel': 'Lowest character level that passes this branch.',
  'content.abilities.requires.anyOf.maxLevel': 'Highest character level that passes this branch.',
  'content.abilities.requires.anyOf.classes': 'Branch passes if the actor is any one of these classes.',
  'content.abilities.requires.anyOf.ancestries': 'Branch passes if the actor is any one of these ancestries.',
  'content.abilities.requires.anyOf.abilities': 'The actor must know all of these for this branch.',
  'content.abilities.requires.anyOf.attributes': 'Attribute bounds this branch checks.',
  'content.abilities.requires.anyOf.skills': 'Skill ranks or tiers this branch checks.',
  'content.abilities.requires.anyOf.creatureTypes': 'Branch passes if the actor is any one of these creature types.',
  'content.abilities.requires.anyOf.alignments': 'Branch passes if the actor is any one of these alignments.',
  'content.abilities.requires.anyOf.languages': 'The actor must speak all of these for this branch.',
  'content.abilities.requires.anyOf.currency': 'Money this branch needs the actor to be carrying.',
  'content.abilities.requires.anyOf.items': 'Items this branch needs.',
  'content.abilities.requires.anyOf.quests': 'Quest statuses this branch checks.',
  'content.abilities.requires.anyOf.factions': 'Faction standing this branch checks.',
  'content.abilities.requires.anyOf.memories': 'Memory this branch checks.',
  'content.abilities.requires.anyOf.flags': 'Flags this branch checks.',
  'content.abilities.requires.anyOf.lore': 'Lore this branch checks.',
  'content.abilities.requires.anyOf.without': 'What this branch needs the actor to lack.',
  'content.abilities.requires.anyOf.custom': 'Raw predicate for this branch. Branches do not nest further.',

  'content.abilities.attack.stat': 'Attribute whose modifier is added to the attack roll.',
  'content.abilities.attack.against': 'Derived stat on the target the roll must meet or beat.',
  'content.abilities.swing': 'Which way this ability\'s own attack roll always leans, before circumstance.',
  'content.abilities.savingThrow.swing': 'Which way the target\'s save against this ability always leans.',

  'content.abilities.savingThrow.save': 'Which save the target rolls.',
  'content.abilities.savingThrow.difficulty': 'Difficulty of that save. Falls back to the save\'s own default.',
  'content.abilities.savingThrow.onSuccess': 'What a success is worth. Nothing, half damage, negated, or partial.',
  'content.abilities.savingThrow.onSuccessEffects': 'Effects run on a successful save, used with partial.',

  'content.abilities.areaOfEffect.shape': 'The volume it covers.',
  'content.abilities.areaOfEffect.size': 'Distance units across, measured by shape.',
  'content.abilities.areaOfEffect.affects': 'Who inside it is caught. Everyone, one side, or everyone but the caster.',
  'content.abilities.areaOfEffect.angle': 'Spread in degrees, for a cone.',

  'content.skills.id': 'Id of the skill, used as actor.skills.<id>.',
  'content.skills.name': 'Display name.',
  'content.skills.description': 'What the skill covers.',
  'content.skills.attribute': 'Attribute whose modifier is added to checks with it.',
  'content.skills.tags': 'Free labels for grouping and gating.',
  'content.skills.extra': 'Open bag of your own data on this skill.',

  'content.ancestries.id': 'Id of the ancestry.',
  'content.ancestries.name': 'Display name.',
  'content.ancestries.description': 'Who these people are.',
  'content.ancestries.tags': 'Free labels for grouping and gating.',
  'content.ancestries.attributeBonuses': 'Attribute adjustments applied at creation.',
  'content.ancestries.grantedAbilities': 'Abilities every member knows from the start.',
  'content.ancestries.skillBonuses': 'Skill rank adjustments applied at creation.',
  'content.ancestries.traits': 'Conditional rules that run for members. A predicate and the effects it gates.',
  'content.ancestries.size': 'Size members are, overriding the ruleset default.',
  'content.ancestries.creatureType': 'Creature type members count as.',
  'content.ancestries.speeds': 'Speed per movement mode, overriding each mode\'s default.',
  'content.ancestries.senses': 'Range per sense, overriding each sense\'s default.',
  'content.ancestries.languages': 'Languages members speak from the start.',
  'content.ancestries.damageInteractions': 'Resistance, vulnerability, and immunity members are born with.',
  'content.ancestries.extra': 'Open bag of your own data on this ancestry.',

  'content.ancestries.damageInteractions.damageType': 'Which damage type this changes.',
  'content.ancestries.damageInteractions.multiplier': 'What incoming damage is multiplied by. 0 is immunity.',
  'content.ancestries.damageInteractions.unless': 'Damage tags that cancel it, so immunity can have an exception.',
  'content.ancestries.damageInteractions.extra': 'Open bag of your own data on this interaction.',

  'content.classes.id': 'Id of the class.',
  'content.classes.name': 'Display name.',
  'content.classes.description': 'What this training is.',
  'content.classes.tags': 'Free labels for grouping and gating.',
  'content.classes.hitDie': 'Die rolled for vitality per level, when levelVitality takes its die from class.',
  'content.classes.attributeBonuses': 'Attribute adjustments applied at creation.',
  'content.classes.primaryAttribute': 'The attribute the class runs on. Read as actor.primaryAttribute.',
  'content.classes.skillProficiencies': 'Skills it trains. A bare skill id, or an object naming a rank.',
  'content.classes.startingItems': 'Gear a new member of the class begins with.',
  'content.classes.abilitiesByLevel': 'Abilities granted, keyed by the level string they arrive at.',
  'content.classes.saveProficiencies': 'Saves the class is proficient in.',
  'content.classes.spellcasting': 'How this class casts, when it casts at all.',
  'content.classes.extra': 'Open bag of your own data on this class.',

  'content.classes.skillProficiencies.skill': 'Which skill is trained.',
  'content.classes.skillProficiencies.rank': 'The rank it is trained to.',

  'content.classes.startingItems.item': 'Which item.',
  'content.classes.startingItems.quantity': 'How many.',

  'content.classes.spellcasting.castingAttribute': 'Attribute that sets save difficulty and attack bonus.',
  'content.classes.spellcasting.spellList': 'Abilities this class may ever learn as spells.',
  'content.classes.spellcasting.progression': 'Multiplier on caster level, for half casters and third casters.',
  'content.classes.spellcasting.knownByLevel': 'How many spells are known, keyed by the level string.',

  'content.items.id': 'Id of the item, used as actor.inventory.<id>.',
  'content.items.name': 'Display name.',
  'content.items.description': 'What it looks like and what it is for.',
  'content.items.kind': 'What sort of thing it is. Decides how the interface treats it.',
  'content.items.tags': 'Free labels. Shops buy by these.',
  'content.items.value': 'Base price in currency. Shops scale it.',
  'content.items.weight': 'Weight carried, summed into actor.carried.',
  'content.items.stackable': 'Not read by the engine. Inventory merges by item id regardless.',
  'content.items.slot': 'Equipment slot it occupies when worn or wielded.',
  'content.items.damage': 'What it deals when used as a weapon.',
  'content.items.modifiers': 'Derived stat adjustments while it is equipped.',
  'content.items.skillBonuses': 'Skill rank added while equipped. Counts for rolls and for minRank gates.',
  'content.items.onUse': 'Effects run when it is used.',
  'content.items.consumedOnUse': 'Whether using it destroys one.',
  'content.items.procs': 'Conditional rules that fire while it is carried. A predicate and its effects.',
  'content.items.grantedAbilities': 'Abilities the holder can use while carrying it.',
  'content.items.rarity': 'Not read by the engine. For display and filtering.',
  'content.items.requiresAttunement': 'Not read by the engine yet, and neither is attunementRequires.',
  'content.items.attunementRequires': 'Ids of what attunement needs. Bare ids, not checked references.',
  'content.items.charges': 'Limited uses, how they come back, and what happens when they run out.',
  'content.items.properties': 'Item properties it carries, each bringing its own modifiers.',
  'content.items.damageInteractions': 'Resistance or vulnerability granted while it is equipped.',
  'content.items.usableBy': 'Classes allowed to use it.',
  'content.items.extra': 'Open bag of your own data on this item.',

  'content.items.damage.dice': 'Damage notation.',
  'content.items.damage.damageType': 'What kind of damage it deals.',
  'content.items.damage.stat': 'Attribute whose modifier is added to the damage.',

  'content.items.charges.max': 'How many charges it holds when full.',
  'content.items.charges.rechargeOn': 'Which rest refills it.',
  'content.items.charges.rechargeAmount': 'How many come back per recharge. Absent means all of them.',
  'content.items.charges.destroyOnEmpty': 'Whether spending the last charge destroys the item.',

  'content.lootTables.id': 'Id of the table.',
  'content.lootTables.name': 'Display name.',
  'content.lootTables.description': 'What this table is for.',
  'content.lootTables.rolls': 'How many times the table is drawn.',
  'content.lootTables.entries': 'The weighted rows. At least one is required.',
  'content.lootTables.emptyChance': 'Chance a draw yields nothing, 0 to 1.',
  'content.lootTables.requires': 'Gate on the whole table. Failing it means no draw at all.',
  'content.lootTables.bonusRollSkill': 'Skill checked on searching, to earn extra draws.',
  'content.lootTables.bonusRolls': 'Extra draws earned by that check.',

  'content.lootTables.entries.weight': 'Relative likelihood against the other rows.',
  'content.lootTables.entries.value': 'What this row yields.',

  'content.lootTables.entries.value.item': 'Which item is found.',
  'content.lootTables.entries.value.quantity': 'How many, as dice notation.',
  'content.lootTables.entries.value.requires': 'Gate on this row. Failing removes it before the draw, not after.',
  'content.lootTables.entries.value.requirementScope': 'Who the gate is measured against. The searcher, the whole party, or any member.',
  'content.lootTables.entries.value.unique': 'Whether the row is removed once it has been found.',

  'content.lootTables.bonusRolls.onSuccess': 'Extra draws for passing the bonus roll skill check.',
  'content.lootTables.bonusRolls.onCritical': 'Extra draws for a critical on that check.',

  'content.monsters.id': 'Id of the statblock. Kill objectives match on it.',
  'content.monsters.name': 'Display name.',
  'content.monsters.description': 'What it looks like.',
  'content.monsters.tags': 'Free labels for grouping and gating.',
  'content.monsters.level': 'Its level, used for scaling and for encounter budgeting.',
  'content.monsters.xp': 'Experience the party gains for killing it. Awarded to everyone.',
  'content.monsters.attributes': 'Its attribute values. Required. Everything else derives from them.',
  'content.monsters.resourceOverrides': 'Formulas replacing the ruleset maximum for named resources.',
  'content.monsters.derivedOverrides': 'Formulas replacing the ruleset formula for named derived stats.',
  'content.monsters.abilities': 'What it can do.',
  'content.monsters.behaviour': 'What it chooses to do, in priority order. Its combat brain.',
  'content.monsters.reactions': 'What it does off its own turn, gated on what it sees and remembers.',
  'content.monsters.loot': 'Table drawn on its death.',
  'content.monsters.conditionalLoot': 'Tables drawn as well as loot, and only when the finder qualifies.',
  'content.monsters.faction': 'Whose side it is on. Decides who it treats as an enemy.',
  'content.monsters.descriptors': 'Adjectives the narrator may reach for.',
  'content.monsters.size': 'Its size, overriding the ruleset default.',
  'content.monsters.creatureType': 'What kind of creature it is.',
  'content.monsters.alignment': 'Its alignment.',
  'content.monsters.damageInteractions': 'Resistance, vulnerability, and immunity.',
  'content.monsters.conditionImmunities': 'Conditions that never land on it.',
  'content.monsters.saveBonuses': 'Flat bonus per saving throw.',
  'content.monsters.skillBonuses': 'Skill rank per skill.',
  'content.monsters.senses': 'Range per sense, overriding each sense\'s default.',
  'content.monsters.speeds': 'Speed per movement mode, overriding each mode\'s default.',
  'content.monsters.languages': 'Languages it speaks.',
  'content.monsters.challenge': 'Not read by the engine. A budgeting number for the editor.',
  'content.monsters.specialTurns': 'Extra turns it takes outside the order. Legendary and lair actions.',
  'content.monsters.extra': 'Open bag of your own data on this monster.',

  'content.monsters.behaviour.priority': 'Higher is considered first. Ties keep declaration order.',
  'content.monsters.behaviour.when': 'Predicate that must hold for this line to be chosen.',
  'content.monsters.behaviour.requires': 'Gate on this line, in the requirement vocabulary.',
  'content.monsters.behaviour.use': 'Ability used when this line is chosen.',

  'content.monsters.reactions.id': 'Id of the reaction.',
  'content.monsters.reactions.description': 'What it does and why.',
  'content.monsters.reactions.on': 'What sets it off.',
  'content.monsters.reactions.event': 'Event name to watch, when on is custom.',
  'content.monsters.reactions.priority': 'Higher is considered first among reactions to the same thing.',
  'content.monsters.reactions.requires': 'Gate measured against the reacting creature, not the party.',
  'content.monsters.reactions.when': 'Predicate checked on top of requires.',
  'content.monsters.reactions.chance': 'Chance it fires once everything else passes, 0 to 1.',
  'content.monsters.reactions.roll': 'A check that decides between onSuccess and onFailure.',
  'content.monsters.reactions.onSuccess': 'Effects run when the roll succeeds.',
  'content.monsters.reactions.onFailure': 'Effects run when the roll fails.',
  'content.monsters.reactions.effects': 'Effects run either way, or when there is no roll.',
  'content.monsters.reactions.use': 'Ability the creature uses as its reaction.',
  'content.monsters.reactions.textKey': 'Text pool narrating it.',
  'content.monsters.reactions.oncePerEncounter': 'Whether it may fire only once per fight.',

  'content.monsters.reactions.roll.skill': 'Skill rolled.',
  'content.monsters.reactions.roll.attribute': 'Attribute rolled, when no skill fits.',
  'content.monsters.reactions.roll.difficulty': 'Difficulty of the roll.',
  'content.monsters.reactions.roll.opposedBy': 'Skill the other side rolls instead of a fixed difficulty.',

  'content.monsters.specialTurns.id': 'Id of the special turn.',
  'content.monsters.specialTurns.name': 'Display name.',
  'content.monsters.specialTurns.use': 'Ability used when it comes round.',
  'content.monsters.specialTurns.uses': 'How many times per round it is available.',
  'content.monsters.specialTurns.when': 'Predicate that must hold for it to be taken.',

  'content.traps.id': 'Id of the trap.',
  'content.traps.name': 'Display name.',
  'content.traps.description': 'What it is once seen.',
  'content.traps.tags': 'Free labels for grouping and gating.',
  'content.traps.detect': 'The check that spots it before it fires.',
  'content.traps.disarm': 'The check that defuses it.',
  'content.traps.onTrigger': 'Effects run on whoever set it off.',
  'content.traps.onDisarm': 'Effects run on a successful disarm.',
  'content.traps.reusable': 'Whether it arms itself again after firing.',

  'content.traps.detect.skill': 'Skill rolled to spot it.',
  'content.traps.detect.difficulty': 'Difficulty of that roll.',
  'content.traps.disarm.skill': 'Skill rolled to defuse it.',
  'content.traps.disarm.difficulty': 'Difficulty of that roll.',

  'content.factions.id': 'Id of the faction, used as reputation.<id>.',
  'content.factions.name': 'Display name.',
  'content.factions.description': 'Who they are and what they want.',
  'content.factions.tags': 'Free labels for grouping and gating.',
  'content.factions.initialStanding': 'Standing the party begins with.',
  'content.factions.relations': 'How this faction feels about others, from minus one to one.',
  'content.factions.ranks': 'Named standing bands, so a gate can ask for a rank rather than a number.',
  'content.factions.decayPerDay': 'Standing pulled back toward zero each day.',

  'content.factions.ranks.id': 'Id of the rank, asked for by a requirement as minRank.',
  'content.factions.ranks.name': 'Display name.',
  'content.factions.ranks.atLeast': 'Standing at which the rank is held.',

  'content.npcs.id': 'Id of the person.',
  'content.npcs.name': 'Display name.',
  'content.npcs.description': 'Who they are.',
  'content.npcs.tags': 'Free labels for grouping and gating.',
  'content.npcs.faction': 'Who they belong to. Deeds against others can reach them through it.',
  'content.npcs.statblock': 'Monster used if they ever have to fight. Without one they cannot.',
  'content.npcs.dialogue': 'What they say. Without one, talking to them does nothing.',
  'content.npcs.home': 'Where they stand. The engine gathers everyone whose home is here on arrival.',
  'content.npcs.gullibility': 'How readily they believe a rumour they did not witness, 0 to 1.',
  'content.npcs.memorySpan': 'Days a deed stays in their memory.',
  'content.npcs.disposition': 'How they feel about the party, from minus one hundred to one hundred.',
  'content.npcs.reactions': 'What they do off their own turn, gated on what they know.',
  'content.npcs.offersQuests': 'The quests they actually put in front of a player. This is what offers work.',
  'content.npcs.shop': 'What they will trade, and on what terms.',
  'content.npcs.caresAbout': 'Deed kinds they take personally. Weighted heavier in their memory.',

  'content.npcs.shop.lootTable': 'Table their stock is drawn from, refreshed daily.',
  'content.npcs.shop.buysTags': 'Item tags they will buy. Anything else they refuse.',
  'content.npcs.shop.priceMultiplier': 'What they scale the base value by.',
  'content.npcs.shop.requires': 'Gate on trading with them at all.',

  // ------------------------------------------------------------------- world
  'world.terrains': 'What a tile can be. Passability and cost are read from here, not baked in.',
  'world.palettes': 'Which terrains a generator builds with. One generator, many looks.',
  'world.biomes': 'A theme. Room templates, encounter tables, ambience, and a palette.',
  'world.areas': 'A named place on the map, belonging to a biome and joined to others.',
  'world.pointsOfInterest': 'Somewhere you go inside an area. A shrine, a camp, a dungeon mouth.',
  'world.gates': 'Something in the way, and what gets you past it.',
  'world.roomTemplates': 'The kinds of room a generated dungeon draws from.',
  'world.encounterTables': 'Weighted groups of monsters, drawn on arrival and in rooms.',
  'world.dungeons': 'A generated interior. Hangs off a point of interest rather than replacing it.',
  'world.maps': 'Hand authored grids, identical on every seed. No randomness is consulted.',
  'world.time': 'The clock. Day length, phases, and what each action costs in minutes.',
  'world.generationDefaults': 'Fallback chances for rooms that name none.',

  'world.terrains.id': 'Id of the terrain, named by palettes, legends, and map cells.',
  'world.terrains.name': 'Display name. Used when something blocks you and has to say why.',
  'world.terrains.description': 'What it looks like underfoot.',
  'world.terrains.tags': 'Free labels for grouping and gating.',
  'world.terrains.glyph': 'One or two characters drawn for it on the map.',
  'world.terrains.color': 'Colour it is drawn in.',
  'world.terrains.passable': 'Whether anything can walk onto it.',
  'world.terrains.opaque': 'Whether it blocks sight and any sense stopped by opaque things.',
  'world.terrains.moveCost': 'Movement spent entering it.',
  'world.terrains.requiresMode': 'Movement modes that can cross it. Empty means any.',
  'world.terrains.providesCover': 'Cover a creature standing here gets.',
  'world.terrains.onEnter': 'Effects run on whoever steps onto it.',
  'world.terrains.onOccupy': 'Effects run on whoever ends their turn on it.',
  'world.terrains.lightRadius': 'Indexed but unread. There is no light model; a sense carries its own reach.',
  'world.terrains.isDoor': 'Indexed but unread. Doors live on the map\'s gate record, not on the terrain.',
  'world.terrains.extra': 'Open bag of your own data on this terrain.',

  'world.palettes.id': 'Id of the palette.',
  'world.palettes.name': 'Display name.',
  'world.palettes.floor': 'Terrain used for open ground.',
  'world.palettes.wall': 'Terrain used for solid rock.',
  'world.palettes.door': 'Terrain used where a corridor meets a room.',
  'world.palettes.scatter': 'Terrains sprinkled over the floor, and how they are spread.',
  'world.palettes.exterior': 'Terrain filling everything outside the built area.',
  'world.palettes.extra': 'Open bag of your own data on this palette.',

  'world.palettes.scatter.terrain': 'Which terrain is scattered.',
  'world.palettes.scatter.frequency': 'Share of floor it covers, 0 to 1.',
  'world.palettes.scatter.distribution': 'Speckle rolls each tile alone. Patch uses noise, so it comes out connected.',
  'world.palettes.scatter.scale': 'Size of the noise features, for patch.',
  'world.palettes.scatter.octaves': 'Layers of noise, for patch. More gives rougher edges.',
  'world.palettes.scatter.edgeTerrain': 'Terrain ringing each patch.',
  'world.palettes.scatter.edgeWidth': 'How many tiles wide that ring is.',
  'world.palettes.scatter.priority': 'Which scatter wins where two overlap. Higher wins.',

  'world.biomes.id': 'Id of the biome.',
  'world.biomes.name': 'Display name.',
  'world.biomes.description': 'What this kind of place is like.',
  'world.biomes.tags': 'Free labels for grouping and gating.',
  'world.biomes.layer': 'Whether places here sit above ground, below it, or either.',
  'world.biomes.roomTemplates': 'Rooms a dungeon in this biome may draw.',
  'world.biomes.encounterTables': 'What may be met here.',
  'world.biomes.lootTables': 'What may be found here.',
  'world.biomes.traps': 'Traps that may be placed here.',
  'world.biomes.ambienceKey': 'Text pool for the background of the place.',
  'world.biomes.triggers': 'Things that happen anywhere in this biome.',
  'world.biomes.palette': 'Terrains generators use here. Overrides a palette named on the map.',
  'world.biomes.extra': 'Open bag of your own data on this biome.',

  'world.biomes.triggers.id': 'Id of the trigger. Also the key under which firing is remembered.',
  'world.biomes.triggers.description': 'What happens and why.',
  'world.biomes.triggers.mode': 'How often it may fire. Choosing this correctly is most of the work.',
  'world.biomes.triggers.on': 'The occasion it listens for.',
  'world.biomes.triggers.event': 'Event name to watch, when on is custom.',
  'world.biomes.triggers.requires': 'Gate on firing, in the requirement vocabulary.',
  'world.biomes.triggers.when': 'Predicate checked on top of requires.',
  'world.biomes.triggers.cooldownMinutes': 'World minutes between firings, for loop mode.',
  'world.biomes.triggers.completeWhen': 'Predicate that ends untilComplete mode once it holds.',
  'world.biomes.triggers.remember': 'Whether the world records that it happened. Off makes the event ambient.',
  'world.biomes.triggers.chance': 'Chance it fires once the gates pass. Rolled last, so a failed gate costs no randomness.',
  'world.biomes.triggers.effects': 'What it does.',
  'world.biomes.triggers.textKey': 'Text pool narrating it.',

  'world.areas.id': 'Id of the area. Its map is keyed area:<id>.',
  'world.areas.name': 'Display name.',
  'world.areas.description': 'What the place is.',
  'world.areas.tags': 'Free labels for grouping and gating.',
  'world.areas.biome': 'Theme it belongs to. Supplies rooms, encounters, ambience, and palette.',
  'world.areas.layer': 'Whether it sits above ground or below. Decides whether the sky is visible.',
  'world.areas.descriptionKey': 'Text pool read on arrival.',
  'world.areas.connections': 'Roads out. Travel is only possible along a declared connection.',
  'world.areas.triggers': 'Things that happen here.',
  'world.areas.encounterTables': 'What may be met here, on top of the biome\'s.',
  'world.areas.controllingFaction': 'Who holds it.',
  'world.areas.dangerLevel': 'How dangerous it is. Feeds the default encounter chance.',
  'world.areas.encounterChance': 'Formula for the chance of an encounter, overriding the danger based default.',
  'world.areas.recommendedLevel': 'Party level the area is written for. Advisory.',
  'world.areas.requires': 'Gate on entering at all.',
  'world.areas.map': 'How the ground here is built. Size, palette, or a hand authored grid.',
  'world.areas.entryPoint': 'Tile the party arrives on. Without one the engine picks a free tile.',
  'world.areas.extra': 'Open bag of your own data on this area.',

  'world.areas.connections.to': 'Area at the other end.',
  'world.areas.connections.travelMinutes': 'World minutes the journey costs.',
  'world.areas.connections.gate': 'Something in the way on this road.',
  'world.areas.connections.oneWay': 'Set on the destination\'s back link. A road listed both ways is two way.',
  'world.areas.connections.encounterTables': 'What may be met on the road itself.',

  'world.areas.map.width': 'Tiles across, as dice notation so it can vary by seed.',
  'world.areas.map.height': 'Tiles down, as dice notation.',
  'world.areas.map.palette': 'Terrains to build with. Dead whenever the biome names one, since the biome wins.',
  'world.areas.map.static': 'A hand authored map to use instead. Beats layout and generation.',
  'world.areas.map.layout': 'Rows of glyphs drawn by hand. Beats generation. All rows must be equal length.',
  'world.areas.map.legend': 'Which terrain each layout glyph means.',
  'world.areas.map.extra': 'Open bag of your own data on this map spec.',

  'world.areas.entryPoint.x': 'Column, counting from zero.',
  'world.areas.entryPoint.y': 'Row, counting from zero.',

  'world.pointsOfInterest.id': 'Id of the place. Its map is keyed poi:<id>.',
  'world.pointsOfInterest.name': 'Display name.',
  'world.pointsOfInterest.description': 'What is here.',
  'world.pointsOfInterest.tags': 'Free labels for grouping and gating.',
  'world.pointsOfInterest.area': 'Area it sits in. A place whose area does not exist never appears.',
  'world.pointsOfInterest.kind': 'What sort of place it is. Decides the icon and some phrasing.',
  'world.pointsOfInterest.descriptionKey': 'Text pool read on arrival.',
  'world.pointsOfInterest.gate': 'Something in the way of going in.',
  'world.pointsOfInterest.hidden': 'Whether it must be found before it can be travelled to.',
  'world.pointsOfInterest.discover': 'The check that finds it. Without one a hidden place stays hidden.',
  'world.pointsOfInterest.triggers': 'Things that happen here.',
  'world.pointsOfInterest.encounterTables': 'What may be met here.',
  'world.pointsOfInterest.encounterChance': 'Chance of an encounter here, overriding the area.',
  'world.pointsOfInterest.residents': 'Who lives here. The other way to place people, alongside an NPC\'s home.',
  'world.pointsOfInterest.loot': 'Tables drawn when the place is searched.',
  'world.pointsOfInterest.dungeon': 'Interior reached from here. The dungeon hangs off the place, it does not replace it.',
  'world.pointsOfInterest.services': 'What can be done here. Trade, rest, healing, training.',
  'world.pointsOfInterest.rumourReach': 'How many hops news of this place travels among its people.',
  'world.pointsOfInterest.controllingFaction': 'Who holds it.',
  'world.pointsOfInterest.travelMinutes': 'World minutes to reach it from the area entrance.',
  'world.pointsOfInterest.position': 'Where it sits on the area map.',
  'world.pointsOfInterest.map': 'How the ground here is built, when the place has an interior of its own.',
  'world.pointsOfInterest.extra': 'Open bag of your own data on this place.',

  'world.pointsOfInterest.discover.skill': 'Skill rolled to find it.',
  'world.pointsOfInterest.discover.difficulty': 'Difficulty of that roll. Often a formula over what the party has heard.',

  'world.gates.id': 'Id of the gate. Its state is flagged gate:<id>:open.',
  'world.gates.name': 'Display name.',
  'world.gates.description': 'What is in the way.',
  'world.gates.tags': 'Free labels for grouping and gating.',
  'world.gates.kind': 'What sort of obstacle it is.',
  'world.gates.requires': 'What opens it outright. Items marked consume are spent doing so.',
  'world.gates.bypass': 'A check that gets past it instead.',
  'world.gates.opensWith': 'Abilities that open it.',
  'world.gates.onOpen': 'Effects run when it opens.',
  'world.gates.onBlocked': 'Effects run when someone fails to open it.',
  'world.gates.blockedTextKey': 'Text pool for being turned away.',
  'world.gates.staysOpen': 'Whether opening it is permanent.',

  'world.gates.bypass.skill': 'Skill rolled to get past.',
  'world.gates.bypass.difficulty': 'Difficulty of that roll.',
  'world.gates.bypass.onSuccess': 'Effects run on getting past.',
  'world.gates.bypass.onFailure': 'Effects run on failing.',
  'world.gates.bypass.retryable': 'Whether a failure may be tried again. False records the attempt and refuses more.',

  'world.roomTemplates.id': 'Id of the template.',
  'world.roomTemplates.name': 'Display name.',
  'world.roomTemplates.tags': 'Free labels for grouping and gating.',
  'world.roomTemplates.descriptionKey': 'Text pool read on first entering a room built from it.',
  'world.roomTemplates.weight': 'Relative likelihood of being drawn against other templates.',
  'world.roomTemplates.role': 'What the room is for. Generation guarantees some roles exist.',
  'world.roomTemplates.minExits': 'Fewest doors the room may have.',
  'world.roomTemplates.maxExits': 'Most doors it may have. Connectivity wins over this cap.',
  'world.roomTemplates.encounterChance': 'Chance the room is occupied, 0 to 1.',
  'world.roomTemplates.trapChance': 'Chance the room is trapped, 0 to 1.',
  'world.roomTemplates.lootChance': 'Chance the room holds something, 0 to 1.',
  'world.roomTemplates.alwaysEncounter': 'Force an occupant regardless of the chance.',
  'world.roomTemplates.neverEncounter': 'Forbid an occupant regardless of the chance.',
  'world.roomTemplates.neverTrap': 'Forbid a trap regardless of the chance.',
  'world.roomTemplates.requires': 'Gate on the template being drawn at all.',
  'world.roomTemplates.triggers': 'Things that happen in a room built from it.',
  'world.roomTemplates.map': 'How the room itself is built.',
  'world.roomTemplates.extra': 'Open bag of your own data on this template.',

  'world.encounterTables.id': 'Id of the table.',
  'world.encounterTables.name': 'Display name.',
  'world.encounterTables.description': 'What this table is for.',
  'world.encounterTables.minDepth': 'Shallowest dungeon depth it may be drawn at.',
  'world.encounterTables.maxDepth': 'Deepest dungeon depth it may be drawn at.',
  'world.encounterTables.chance': 'Chance a draw yields anything at all, 0 to 1.',
  'world.encounterTables.emptyWeight': 'Weight of the nothing row against the groups.',
  'world.encounterTables.scalePerLevels': 'Party levels per step of scaling on entries that scale.',
  'world.encounterTables.groups': 'The weighted rows. Each is a whole encounter.',

  'world.encounterTables.groups.id': 'Id of the group.',
  'world.encounterTables.groups.name': 'Display name.',
  'world.encounterTables.groups.weight': 'Relative likelihood against the other groups.',
  'world.encounterTables.groups.requires': 'Gate on the group. Failing removes it before the draw, not after.',
  'world.encounterTables.groups.entries': 'The creatures in it. At least one is required.',
  'world.encounterTables.groups.onEncounter': 'Effects run when this group is drawn.',
  'world.encounterTables.groups.textKey': 'Text pool narrating the meeting.',
  'world.encounterTables.groups.hostile': 'Whether they attack. False makes it a meeting rather than a fight.',

  'world.encounterTables.groups.entries.monster': 'Which statblock appears.',
  'world.encounterTables.groups.entries.count': 'How many, as dice notation.',
  'world.encounterTables.groups.entries.scaleWithLevel': 'Whether the count grows with party level.',

  'world.dungeons.id': 'Id of the dungeon. Its maps are keyed by it and the depth.',
  'world.dungeons.name': 'Display name.',
  'world.dungeons.description': 'What is down there.',
  'world.dungeons.biome': 'Theme it is built from. Supplies room templates and encounters.',
  'world.dungeons.roomCount': 'Rooms requested per floor. A request, not a promise; packing may fit fewer.',
  'world.dungeons.depth': 'How many floors deep it goes.',
  'world.dungeons.branchiness': 'Extra loops added past the spanning tree, 0 to 1. 0 gives a pure tree.',
  'world.dungeons.lockedDoorChance': 'Chance a tree edge gets a lock. Keys are always placed before their lock.',
  'world.dungeons.doorGates': 'Gates that may be used as locks.',
  'world.dungeons.guaranteedRoles': 'Room roles that must exist. Bare strings, not checked references.',
  'world.dungeons.safeEntrance': 'Whether the entrance room is guaranteed empty.',
  'world.dungeons.bossTable': 'Drawn in the boss room. Without one the deepest room generates like any other.',
  'world.dungeons.completionTriggers': 'Things that happen when the dungeon is finished.',
  'world.dungeons.palette': 'Terrains to build with, overriding the biome.',
  'world.dungeons.corridorLength': 'Corridor length, which is what actually sets the spacing between rooms.',
  'world.dungeons.winding': 'How much corridors wander, when the corridor style is winding.',
  'world.dungeons.roomSize': 'How large a room is on a side.',
  'world.dungeons.algorithm': 'How the floor is carved. Placed rooms, split rectangles, or grown caves.',
  'world.dungeons.bsp': 'Settings for the bsp algorithm.',
  'world.dungeons.caverns': 'Settings for the caverns algorithm.',
  'world.dungeons.staticMap': 'A hand authored map to use instead. Skips generation entirely.',
  'world.dungeons.rollEncounters': 'Whether rooms roll their own encounters as well as the placed ones.',
  'world.dungeons.corridor': 'Shape and width of the corridors.',
  'world.dungeons.width': 'Floor width in tiles. Without one the engine sizes it from the room count.',
  'world.dungeons.height': 'Floor height in tiles.',
  'world.dungeons.extra': 'Open bag of your own data on this dungeon.',

  'world.dungeons.winding.continueChance': 'Chance a corridor keeps going the way it was, 0 to 1.',
  'world.dungeons.winding.turnPenalty': 'How much a turn is discouraged, 0 to 1.',

  'world.dungeons.bsp.minLeaf': 'Smallest rectangle the splitting stops at.',

  'world.dungeons.caverns.fill': 'Share of the floor filled with rock before smoothing, 0 to 1.',
  'world.dungeons.caverns.smoothingPasses': 'How many rounds of smoothing are run.',
  'world.dungeons.caverns.birthThreshold': 'Neighbours needed for a cell to become rock.',

  'world.dungeons.corridor.style': 'Whether corridors turn once, run straight, or wander.',
  'world.dungeons.corridor.width': 'Tiles across. Crossings are never widened, so a locked door stays one tile.',

  'world.maps.id': 'Id of the map, named by an area, place, dungeon, or room template.',
  'world.maps.name': 'Display name.',
  'world.maps.description': 'What this map is.',
  'world.maps.tags': 'Free labels for grouping and gating.',
  'world.maps.entry': 'Marker the party arrives at.',
  'world.maps.layers': 'Grids stacked in draw order. The layer kind decides what its cells mean.',
  'world.maps.extra': 'Open bag of your own data on this map.',

  'world.maps.layers.kind': 'What the cells name. Terrain, items, monsters, npcs, gates, traps, or free markers.',
  'world.maps.layers.name': 'Names the layer in the editor and its file on disk.',
  'world.maps.layers.cells': 'Rows of ids, one per tile. An empty cell means nothing here.',
  'world.maps.layers.extra': 'Open bag of your own data on this layer.',

  'world.time.minutesPerDay': 'How long a day is.',
  'world.time.minutesPerHour': 'How long an hour is.',
  'world.time.daysPerMonth': 'How long a month is.',
  'world.time.monthNames': 'Names of the months, in order.',
  'world.time.dayPhases': 'Named parts of the day and when each begins.',
  'world.time.startMinute': 'Minute of the first day play begins at.',
  'world.time.actionMinutes': 'World minutes each action costs outside combat.',
  'world.time.minutesPerTile': 'World minutes a step costs. Only charged outside combat.',

  'world.time.dayPhases.id': 'Id of the phase, read as world.phase.',
  'world.time.dayPhases.name': 'Display name.',
  'world.time.dayPhases.startMinute': 'Minute of the day it begins at.',

  'world.generationDefaults.encounterChance': 'Encounter chance for a room whose template names none.',
  'world.generationDefaults.lootChance': 'Loot chance for a room whose template names none.',
  'world.generationDefaults.trapChance': 'Trap chance for a room whose template names none.',

  // --------------------------------------------------------------- narrative
  'narrative.maxDialogueHops': 'How many redirects a conversation may follow before it stops.',
  'narrative.textGrammar': 'Weighted pools of phrasing. Where variety in the prose comes from.',
  'narrative.systemText': 'Every sentence the engine itself produces. It holds no prose of its own.',
  'narrative.dialogues': 'Conversation graphs. An NPC points at one; the dialogue does not name its owner.',
  'narrative.quests': 'Jobs, their objectives, and what finishing them is worth.',
  'narrative.arcs': 'Groups of quests read as one story. One of them may end the game.',
  'narrative.lore': 'Things that can be known. Taught only by a learnLore effect.',
  'narrative.loreThreads': 'Lore grouped into a mystery, so a journal can say three of five.',
  'narrative.deedKinds': 'The kinds of thing the party can be remembered for.',
  'narrative.memory': 'How people witness, forget, gossip, and learn. A settings block, not a collection.',

  'narrative.textGrammar.id': 'Id of the pool, named wherever prose is wanted.',
  'narrative.textGrammar.description': 'What this pool is for.',
  'narrative.textGrammar.variants': 'The phrasings. At least one is required.',

  'narrative.textGrammar.variants.text': 'The sentence. Placeholders in braces are filled from the facts in scope.',
  'narrative.textGrammar.variants.when': 'Predicate gating this phrasing, so prose can react to world state.',
  'narrative.textGrammar.variants.requires': 'Gate on this phrasing, in the requirement vocabulary.',
  'narrative.textGrammar.variants.weight': 'Relative likelihood against the other phrasings.',
  'narrative.textGrammar.variants.tags': 'Free labels for grouping.',

  'narrative.dialogues.id': 'Id of the dialogue. An NPC names it to own it.',
  'narrative.dialogues.start': 'Node the conversation opens on. Must be one of the nodes below.',
  'narrative.dialogues.nodes': 'The nodes. Navigation between them is by node id inside this dialogue only.',

  'narrative.dialogues.nodes.id': 'Id of the node, unique inside this dialogue.',
  'narrative.dialogues.nodes.says': 'What the speaker says. Weighted phrasings, picked on entering.',
  'narrative.dialogues.nodes.onEnter': 'Effects run on entering. Where a checked payoff belongs.',
  'narrative.dialogues.nodes.remembers': 'Deed kind recorded when this node is reached.',
  'narrative.dialogues.nodes.redirectWhen': 'Send the player elsewhere before speaking. First match wins.',
  'narrative.dialogues.nodes.options': 'Replies offered. A node with none ends the conversation.',

  'narrative.dialogues.nodes.redirectWhen.requires': 'Gate on taking this redirect.',
  'narrative.dialogues.nodes.redirectWhen.goto': 'Node to jump to instead.',

  'narrative.dialogues.nodes.options.id': 'Id of the option. Also the key under which taking it is remembered.',
  'narrative.dialogues.nodes.options.text': 'What the player says.',
  'narrative.dialogues.nodes.options.requires': 'Gate on the option, measured against what the speaker knows.',
  'narrative.dialogues.nodes.options.when': 'Predicate checked on top of requires.',
  'narrative.dialogues.nodes.options.showWhenLocked': 'Show it greyed out when gated, rather than hiding it.',
  'narrative.dialogues.nodes.options.lockedHint': 'What to say about why it is closed.',
  'narrative.dialogues.nodes.options.check': 'A roll that decides where the option leads.',
  'narrative.dialogues.nodes.options.effects': 'Effects run on choosing it, before and regardless of any check.',
  'narrative.dialogues.nodes.options.onceOnly': 'Whether it may be taken only once, remembered across conversations.',
  'narrative.dialogues.nodes.options.goto': 'Node it leads to. Omit to end the conversation.',

  'narrative.quests.id': 'Id of the quest, used as quests.<id>.status.',
  'narrative.quests.name': 'Display name.',
  'narrative.quests.description': 'What the job is.',
  'narrative.quests.tags': 'Free labels for grouping and gating.',
  'narrative.quests.available': 'Predicate deciding whether it can be offered yet.',
  'narrative.quests.autoStart': 'Whether it begins on its own when play starts.',
  'narrative.quests.giver': 'A label. What actually puts the job in front of a player is that NPC\'s offersQuests.',
  'narrative.quests.requires': 'Gate on taking it.',
  'narrative.quests.stages': 'Ordered chapters, each holding its own objectives. The current one is derived.',
  'narrative.quests.objectives': 'Objectives held directly on the quest rather than in a stage.',
  'narrative.quests.ordered': 'Whether objectives must be finished in order.',
  'narrative.quests.onStart': 'Effects run when it begins.',
  'narrative.quests.onComplete': 'Effects run when it is finished.',
  'narrative.quests.onFail': 'Effects run when it fails.',
  'narrative.quests.failWhen': 'Predicate that fails the quest once it holds.',
  'narrative.quests.rewards': 'Experience, items, and standing paid on completion.',
  'narrative.quests.unlocks': 'Quests marked available when this one finishes. How a chain is wired.',
  'narrative.quests.remembersAs': 'Deed kind recorded when it is finished, so people can hear about it.',
  'narrative.quests.repeatable': 'Whether it can be taken again after finishing.',
  'narrative.quests.timeLimitDays': 'Days before it fails on its own.',

  'narrative.quests.stages.id': 'Id of the stage.',
  'narrative.quests.stages.name': 'Display name.',
  'narrative.quests.stages.description': 'What this chapter is.',
  'narrative.quests.stages.objectives': 'What must be done to move past it.',
  'narrative.quests.stages.onStart': 'Effects run when the stage becomes current.',
  'narrative.quests.stages.onComplete': 'Effects run when the stage is finished.',
  'narrative.quests.stages.journalKey': 'Text pool for the journal entry while this stage is current.',

  'narrative.quests.objectives.id': 'Id of the objective, used as quests.<quest>.objectives.<id>.',
  'narrative.quests.objectives.description': 'What to do, as the journal puts it.',
  'narrative.quests.objectives.kind': 'What kind of event finishes it. Custom watches your own predicate.',
  'narrative.quests.objectives.target': 'What to kill, collect, reach, or talk to. A bare id, not a checked reference.',
  'narrative.quests.objectives.count': 'How many times it must happen.',
  'narrative.quests.objectives.when': 'Required for custom. On other kinds, an extra gate the event must also pass.',
  'narrative.quests.objectives.requires': 'Gate on the objective accepting progress at all.',
  'narrative.quests.objectives.hidden': 'Whether it is kept out of the journal until finished.',
  'narrative.quests.objectives.optional': 'Whether the quest can finish without it.',
  'narrative.quests.objectives.onComplete': 'Effects run when it is finished.',

  'narrative.quests.rewards.xp': 'Experience paid, as an expression. Awarded to the whole party.',
  'narrative.quests.rewards.items': 'Items handed over.',
  'narrative.quests.rewards.reputation': 'Standing change per faction, each as an expression.',

  'narrative.quests.rewards.items.item': 'Which item.',
  'narrative.quests.rewards.items.quantity': 'How many, as an expression.',

  'narrative.arcs.id': 'Id of the arc, read as arcs.<id>.',
  'narrative.arcs.name': 'Display name.',
  'narrative.arcs.description': 'What this story is.',
  'narrative.arcs.quests': 'The quests it is made of. At least one is required.',
  'narrative.arcs.isEnding': 'Finishing it ends the run, unless start.postVictory says continue.',

  'narrative.lore.id': 'Id of the entry, read as lore.<id>.',
  'narrative.lore.name': 'Display name.',
  'narrative.lore.description': 'What is known.',
  'narrative.lore.tags': 'Free labels for grouping and gating.',
  'narrative.lore.textKey': 'Text pool for how it reads when learned.',
  'narrative.lore.source': 'Where it came from, for the journal.',

  'narrative.loreThreads.id': 'Id of the thread, read as threads.<id>.known.',
  'narrative.loreThreads.name': 'Display name.',
  'narrative.loreThreads.description': 'What the mystery is.',
  'narrative.loreThreads.entries': 'The lore that makes it up. At least one is required.',

  'narrative.deedKinds.id': 'Id of the deed kind, read as memory.<who>.<id>.',
  'narrative.deedKinds.name': 'Display name.',
  'narrative.deedKinds.tags': 'Free labels for grouping and gating.',
  'narrative.deedKinds.severity': 'How bad it is. Gossip below the minimum severity never travels.',
  'narrative.deedKinds.faction': 'Who takes it personally. Without one, derived from the victim.',
  'narrative.deedKinds.memorability': 'How strongly it lodges. Multiplies against the forgetting curve.',
  'narrative.deedKinds.distortion': 'How much the story changes as it is retold, 0 to 1.',

  'narrative.memory.mode': 'Whether the engine drives memory, your content drives it, or both.',
  'narrative.memory.forgetting': 'How a memory fades.',
  'narrative.memory.gossip': 'How news travels between people.',
  'narrative.memory.witness': 'Who sees a deed and whether they can name who did it.',
  'narrative.memory.learning': 'Whether creatures adapt to how the party fights.',
  'narrative.memory.rules': 'Per deed kind overrides and hand placed knowledge.',
  'narrative.memory.extra': 'Open bag of your own data on the memory model.',

  'narrative.memory.forgetting.curve': 'Shape of the fade. None keeps a memory forever.',
  'narrative.memory.forgetting.halfLifeDays': 'Days for a memory to lose half its strength.',
  'narrative.memory.forgetting.floor': 'Strength it never fades below, 0 to 1.',
  'narrative.memory.forgetting.reinforceOnRecall': 'Strength returned each time the memory comes up.',
  'narrative.memory.forgetting.memorabilityWeight': 'How much a deed kind\'s memorability slows the fade.',
  'narrative.memory.forgetting.caresAboutMultiplier': 'How much slower it fades for someone who cares about it.',
  'narrative.memory.forgetting.linearSpanMultiplier': 'Half lives a linear curve takes to reach nothing.',
  'narrative.memory.forgetting.neverForget': 'Deed kinds that never fade at all.',
  'narrative.memory.forgetting.extra': 'Open bag of your own data on forgetting.',

  'narrative.memory.gossip.enabled': 'Whether news travels at all.',
  'narrative.memory.gossip.spreadPerDay': 'Chance per day that a knower tells someone, 0 to 1.',
  'narrative.memory.gossip.maxHops': 'How far from the witness a story can travel.',
  'narrative.memory.gossip.hopRetention': 'Strength kept per hop, 0 to 1.',
  'narrative.memory.gossip.distortionPerHop': 'How much the story changes per hop, 0 to 1.',
  'narrative.memory.gossip.requiresTravel': 'Whether news needs someone to actually go there.',
  'narrative.memory.gossip.crossFactionRate': 'How readily it crosses between factions, 0 to 1.',
  'narrative.memory.gossip.minimumSeverity': 'Deeds below this are not worth repeating.',
  'narrative.memory.gossip.gullibilityScale': 'How much a listener\'s gullibility decides whether they believe it.',
  'narrative.memory.gossip.garbledRetention': 'Strength kept once a story has become distorted, 0 to 1.',
  'narrative.memory.gossip.spreadsWithoutWitness': 'Whether a deed nobody saw can still become a rumour.',
  'narrative.memory.gossip.extra': 'Open bag of your own data on gossip.',

  'narrative.memory.witness.radius': 'Tiles within which a deed is seen. 0 uses the perception model instead.',
  'narrative.memory.witness.requiresLineOfSight': 'Whether a witness must be able to see it.',
  'narrative.memory.witness.deadMenTellNoTales': 'Whether killing the witnesses stops the news.',
  'narrative.memory.witness.identificationChance': 'Chance a witness can name who did it, 0 to 1.',
  'narrative.memory.witness.disguiseReduction': 'How much a concealing condition cuts that chance, 0 to 1.',
  'narrative.memory.witness.factionAlwaysLearns': 'Whether the victim\'s faction hears regardless of witnesses.',
  'narrative.memory.witness.extra': 'Open bag of your own data on witnessing.',

  'narrative.memory.learning.enabled': 'Whether creatures adapt to the party at all.',
  'narrative.memory.learning.encountersBeforeAdapting': 'Fights needed before anything changes.',
  'narrative.memory.learning.adaptationStrength': 'How far behaviour shifts once it does, 0 to 1.',
  'narrative.memory.learning.sharedWithinFaction': 'Whether what one learns the rest know.',
  'narrative.memory.learning.minimumIntellect': 'Attribute value below which a creature cannot learn.',
  'narrative.memory.learning.tracks': 'What is noticed about the party.',
  'narrative.memory.learning.forgetAfterDays': 'Days before what was learned is lost.',
  'narrative.memory.learning.extra': 'Open bag of your own data on learning.',

  'narrative.memory.rules.id': 'Id of the rule.',
  'narrative.memory.rules.name': 'Display name.',
  'narrative.memory.rules.description': 'What this rule is for.',
  'narrative.memory.rules.deedKinds': 'Deed kinds it applies to. Empty means all of them.',
  'narrative.memory.rules.when': 'Predicate gating the rule.',
  'narrative.memory.rules.alwaysKnownBy': 'People who know regardless of witnesses or gossip.',
  'narrative.memory.rules.neverKnownBy': 'People who never find out.',
  'narrative.memory.rules.spreadPerDay': 'Gossip rate for these deeds, overriding the global one.',
  'narrative.memory.rules.halfLifeDays': 'Forgetting half life for these deeds, overriding the global one.',
  'narrative.memory.rules.distortionPerHop': 'Distortion for these deeds, overriding the global one.',
  'narrative.memory.rules.manualOnly': 'Whether the simulation leaves these deeds entirely to your content.',
  'narrative.memory.rules.extra': 'Open bag of your own data on this rule.',

  // ------------------------------------------------------------------- start
  'start.partySize': 'How many characters the player makes and runs.',
  'start.creation': 'How those characters are built.',
  'start.startingArea': 'Used only if no starting point of interest or dungeon is set.',
  'start.startingPoi': 'Place play begins at. Beats startingArea.',
  'start.startingDungeon': 'Dungeon play begins in. Beats both of the above.',
  'start.openingTextKey': 'Text pool read before anything else.',
  'start.partyFollow': 'How characters you are not steering keep up with you.',
  'start.initialFlags': 'World flags set before play begins.',
  'start.victoryWhen': 'Predicate that ends the run in victory once it holds.',
  'start.defeatWhen': 'Predicate that ends the run in defeat once it holds. A dead party is always defeat.',
  'start.postVictory': 'Whether reaching an ending stops play or lets it carry on.',

  'start.creation.attributePoints': 'Points available to spend on attributes.',
  'start.creation.attributeCosts': 'Cost to reach each attribute value, keyed by the value.',
  'start.creation.startingLevel': 'Level characters begin at.',
  'start.creation.skillRanks': 'Skill ranks available to spend.',
  'start.creation.allowedAncestries': 'Ancestries offered. Empty offers all of them.',
  'start.creation.allowedClasses': 'Classes offered. Empty offers all of them.',
  'start.creation.startingItems': 'Gear every character begins with, on top of their class kit.',
  'start.creation.startingCurrency': 'Money the party begins with.',

  'start.creation.startingItems.item': 'Which item.',
  'start.creation.startingItems.quantity': 'How many.',

  'start.partyFollow.catchUpDistance': 'Tiles behind before a follower hurries.',
  'start.partyFollow.catchUpSteps': 'Extra steps a hurrying follower takes.',
};
