/**
 * The map viewport: what a place actually looks like, generated by the real
 * engine from a chosen seed.
 *
 * Rendering is a single canvas (maps reach 60×40+; a DOM grid would churn on
 * every keystroke) with markers in an absolutely-positioned overlay so their
 * tooltips are plain DOM. The explainer strip answers the question the studio
 * exists to answer: is this map authored or seed-generated, and what put
 * everything where it is.
 */

import { useEffect, useMemo, useRef, useState } from 'react';
import type { ModuleStore } from '@/lib/store';
import {
  compileForPreview, previewArea, previewDungeon, previewPoi, previewRoomTemplate, previewStart,
} from '@/lib/preview';
import type { PreviewResult } from '@/lib/preview';
import { terrainColor } from '@/lib/terrainColors';
import type { PreviewTarget } from '@/app/studio/selection';
import { MapGenerationPanel } from './MapGenerationPanel';
import styles from '@/app/studio/studio.module.css';

const TILE = 18;
const DEFAULT_SEED = 12345;

export function MapViewport(props: { store: ModuleStore; target: PreviewTarget }) {
  const [seed, setSeed] = useState(DEFAULT_SEED);
  const [showMarkers, setShowMarkers] = useState(true);
  const [showRooms, setShowRooms] = useState(true);
  // Open by default: the complaint this answers is that the controls could not
  // be found, and a drawer that starts shut would not answer it.
  const [showControls, setShowControls] = useState(true);

  const doc = props.store.doc;
  const module = useMemo(() => compileForPreview(doc), [doc]);

  const result: PreviewResult | null = useMemo(() => {
    if (!module) return null;
    switch (props.target.type) {
      case 'start':
        return previewStart(module, seed);
      case 'area':
        return previewArea(module, props.target.id, seed);
      case 'poi':
        return previewPoi(module, props.target.id, seed);
      case 'dungeon':
        return previewDungeon(module, props.target.id, seed);
      case 'roomTemplate':
        return previewRoomTemplate(module, props.target.id, seed);
    }
  }, [module, props.target, seed]);

  const title =
    props.target.type === 'start' ? 'Game start' : `${props.target.type}: ${props.target.id}`;

  return (
    <>
      <div className={styles.mapTools}>
        <span className={styles.mapBadge}>{title}</span>
        {result?.ok && (
          <span
            className={`${styles.mapBadge} ${result.preview.authored ? styles.mapBadgeAuthored : styles.mapBadgeGenerated}`}
            title={
              result.preview.authored
                ? 'This layout is hand-authored in the module; the seed has no effect on it.'
                : 'This map is generated from the seed by the engine at play time.'
            }
          >
            {result.preview.authored ? '✎ authored' : '🎲 generated'}
          </span>
        )}
        <label>
          seed
          <input
            className={`input ${styles.seedInput}`}
            type="number"
            value={seed}
            disabled={result?.ok === true && result.preview.authored}
            onChange={(e) => setSeed(Number(e.target.value) || 0)}
          />
        </label>
        <button
          className="btn tiny"
          title="Try another seed"
          disabled={result?.ok === true && result.preview.authored}
          onClick={() => setSeed(Math.floor(Math.random() * 1_000_000))}
        >
          ⟳ re-roll
        </button>
        <label>
          <input type="checkbox" checked={showMarkers} onChange={(e) => setShowMarkers(e.target.checked)} />
          markers
        </label>
        <label>
          <input type="checkbox" checked={showRooms} onChange={(e) => setShowRooms(e.target.checked)} />
          rooms
        </label>
        <button
          className={`btn tiny ${showControls ? 'primary' : ''}`}
          title="The fields that decide what this map looks like"
          onClick={() => setShowControls(!showControls)}
        >
          ⚙ generation
        </button>
      </div>

      <div className={styles.mapBody}>
        <div className={styles.mapColumn}>
          {!module && (
            <div className={styles.mapScroll}>
              <p className={styles.mapMessage}>
                The module has <code>errors</code> — the engine cannot compile it, so nothing can be
                generated. Fix the problems in the console below and the preview appears.
              </p>
            </div>
          )}

          {module && result && !result.ok && (
            <div className={styles.mapScroll}>
              <p className={styles.mapMessage}>{result.message}</p>
            </div>
          )}

          {module && result?.ok && (
            <>
              <MapCanvas
                preview={result.preview}
                showMarkers={showMarkers}
                showRooms={showRooms}
              />
              <div className={styles.mapSide}>
                <div className={styles.mapExplain}>
                  {result.preview.explain.map((line, i) => (
                    <p key={i}>{line}</p>
                  ))}
                  {!result.preview.authored && (
                    <p>
                      <strong>Why a seed?</strong> The module stores no tiles for generated places — a
                      runtime seed decides them, and the first visit freezes the result into the save.
                    </p>
                  )}
                </div>
                <Legend tiles={result.preview.tiles} />
              </div>
            </>
          )}
        </div>

        {/* Deliberately outside every `module &&` guard above. Half-typed dice
            notation stops the module compiling, and controls that vanished at
            that moment could not be used to type the rest. */}
        {showControls && (
          <MapGenerationPanel
            store={props.store}
            target={props.target}
            authored={result?.ok === true && result.preview.authored}
          />
        )}
      </div>
    </>
  );
}

function MapCanvas(props: {
  preview: { tiles: { width: number; height: number; tiles: readonly string[] }; markers: readonly { x: number; y: number; glyph: string; label: string }[]; rooms: readonly { x: number; y: number; width: number; height: number; role: string }[] };
  showMarkers: boolean;
  showRooms: boolean;
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [hover, setHover] = useState<{ x: number; y: number; terrain: string } | null>(null);
  const { tiles, markers, rooms } = props.preview;

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ratio = window.devicePixelRatio || 1;
    canvas.width = tiles.width * TILE * ratio;
    canvas.height = tiles.height * TILE * ratio;
    canvas.style.width = `${tiles.width * TILE}px`;
    canvas.style.height = `${tiles.height * TILE}px`;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    ctx.scale(ratio, ratio);

    for (let y = 0; y < tiles.height; y += 1) {
      for (let x = 0; x < tiles.width; x += 1) {
        const terrain = tiles.tiles[y * tiles.width + x] ?? '';
        ctx.fillStyle = terrainColor(terrain);
        ctx.fillRect(x * TILE, y * TILE, TILE, TILE);
      }
    }

    // A faint grid keeps tiles countable without shouting.
    ctx.strokeStyle = 'rgba(0, 0, 0, 0.18)';
    ctx.lineWidth = 1;
    for (let x = 0; x <= tiles.width; x += 1) {
      ctx.beginPath();
      ctx.moveTo(x * TILE + 0.5, 0);
      ctx.lineTo(x * TILE + 0.5, tiles.height * TILE);
      ctx.stroke();
    }
    for (let y = 0; y <= tiles.height; y += 1) {
      ctx.beginPath();
      ctx.moveTo(0, y * TILE + 0.5);
      ctx.lineTo(tiles.width * TILE, y * TILE + 0.5);
      ctx.stroke();
    }

    if (props.showRooms) {
      ctx.strokeStyle = 'rgba(217, 164, 65, 0.55)';
      ctx.lineWidth = 1.5;
      for (const room of rooms) {
        ctx.strokeRect(room.x * TILE + 1, room.y * TILE + 1, room.width * TILE - 2, room.height * TILE - 2);
      }
    }
  }, [tiles, rooms, props.showRooms]);

  return (
    <div className={styles.mapScroll}>
      <div className={styles.mapCanvasWrap}>
        <canvas
          ref={canvasRef}
          className={styles.mapCanvas}
          onMouseMove={(e) => {
            const rect = e.currentTarget.getBoundingClientRect();
            const x = Math.floor((e.clientX - rect.left) / TILE);
            const y = Math.floor((e.clientY - rect.top) / TILE);
            if (x < 0 || y < 0 || x >= tiles.width || y >= tiles.height) {
              setHover(null);
              return;
            }
            setHover({ x, y, terrain: tiles.tiles[y * tiles.width + x] ?? '' });
          }}
          onMouseLeave={() => setHover(null)}
        />
        {props.showMarkers &&
          markers.map((marker, i) => (
            <span
              key={i}
              className={styles.mapMarker}
              style={{ left: 24 + marker.x * TILE + TILE / 2, top: 24 + marker.y * TILE + TILE / 2 }}
              title={marker.label}
            >
              {marker.glyph}
            </span>
          ))}
        {hover && (
          <span
            className={styles.mapHover}
            style={{ left: 24 + hover.x * TILE + TILE, top: 24 + hover.y * TILE - TILE }}
          >
            {hover.x},{hover.y} <code>{hover.terrain}</code>
          </span>
        )}
      </div>
    </div>
  );
}

/** Every terrain on this map, with its color and passability. */
function Legend(props: { tiles: { tiles: readonly string[] } }) {
  const ids = useMemo(() => [...new Set(props.tiles.tiles)].sort(), [props.tiles]);
  return (
    <div className={styles.legend}>
      {ids.map((id) => (
        <span className={styles.legendRow} key={id}>
          <span className={styles.legendSwatch} style={{ background: terrainColor(id) }} />
          <span className={styles.legendId}>{id || '(empty)'}</span>
        </span>
      ))}
    </div>
  );
}
